// @vitest-environment jsdom
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';

const root=process.cwd().endsWith('/worker')?resolve(process.cwd(),'..'):process.cwd();
const source=name=>readFileSync(resolve(root,'miniapp',name),'utf8');
beforeAll(()=>window.eval(source('draft-store.js')));
beforeEach(()=>{document.body.innerHTML='';vi.useRealTimers()});

function harness(initial={content:'',plainText:'',images:[],activePhotoIndex:0,platform:'telegram'}){
  let snapshot={...initial,version:0},version=0;const listeners=new Set();
  return {state:{getSnapshot:()=>snapshot,getVersion:()=>version,subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn)),restore:value=>{snapshot={...snapshot,...value,version:++version}},reset:()=>{snapshot={content:'',plainText:'',images:[],activePhotoIndex:0,platform:'telegram',version:++version}}},change(fields,next={}){snapshot={...snapshot,...next,version:++version};listeners.forEach(fn=>fn({fields,reason:fields.join(','),snapshot,version}))},snapshot:()=>snapshot};
}
const response=(ok=true,draft=null,status=ok?200:500)=>({ok,status,json:async()=>({draft})});
function setup(h,fetchImpl=vi.fn(async()=>response())){return {store:window.CosmoDraftStoreFactory.create({state:h.state,fetchImpl,authHeaders:()=>({Authorization:'test'})}),fetchImpl}}

describe('DraftStore',()=>{
  it('coalesces rapid changes after four seconds',async()=>{vi.useFakeTimers();const h=harness(),{store,fetchImpl}=setup(h);h.change(['content'],{content:'a',plainText:'a'});h.change(['content'],{content:'ab',plainText:'ab'});await vi.advanceTimersByTimeAsync(3999);expect(fetchImpl).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(1);expect(fetchImpl).toHaveBeenCalledOnce();store.dispose()});
  it('moves its trailing timer on a new change',async()=>{vi.useFakeTimers();const h=harness(),{store,fetchImpl}=setup(h);h.change(['content'],{content:'a',plainText:'a'});await vi.advanceTimersByTimeAsync(3000);h.change(['content'],{content:'b',plainText:'b'});await vi.advanceTimersByTimeAsync(3999);expect(fetchImpl).not.toHaveBeenCalled();await vi.advanceTimersByTimeAsync(1);expect(fetchImpl).toHaveBeenCalledOnce();store.dispose()});
  it('flushes pending work immediately',async()=>{vi.useFakeTimers();const h=harness(),{store,fetchImpl}=setup(h);h.change(['content'],{content:'now',plainText:'now'});await store.flush('preview');expect(fetchImpl).toHaveBeenCalledOnce();await vi.runAllTimersAsync();expect(fetchImpl).toHaveBeenCalledOnce();store.dispose()});
  it('omits images from text-only saves',async()=>{const image=new File(['x'],'x.jpg'),h=harness({content:'',plainText:'',images:[image],activePhotoIndex:0,platform:'telegram'}),{store,fetchImpl}=setup(h);h.change(['content'],{content:'text',plainText:'text'});await store.flush();expect(fetchImpl.mock.calls[0][1].body.get('imagesChanged')).toBe('0');expect(fetchImpl.mock.calls[0][1].body.getAll('images')).toHaveLength(0);store.dispose()});
  it('sends a changed image set only once',async()=>{const image=new File(['x'],'x.jpg'),h=harness(),{store,fetchImpl}=setup(h);h.change(['images'],{images:[image]});await store.flush();h.change(['activePhotoIndex'],{activePhotoIndex:0});await store.flush();expect(fetchImpl.mock.calls[0][1].body.get('imagesChanged')).toBe('1');expect(fetchImpl.mock.calls[1][1].body.get('imagesChanged')).toBe('0');store.dispose()});
  it('preserves a change made during an in-flight save',async()=>{let release;const fetchImpl=vi.fn().mockImplementationOnce(()=>new Promise(r=>release=r)).mockResolvedValue(response()),h=harness(),{store}=setup(h,fetchImpl);h.change(['content'],{content:'one',plainText:'one'});void store.flush();h.change(['content'],{content:'two',plainText:'two'});release(response());await vi.waitFor(()=>expect(fetchImpl).toHaveBeenCalledTimes(2));expect(fetchImpl.mock.calls[1][1].body.get('text')).toBe('two');store.dispose()});
  it('runs a follow-up after a successful stale save',async()=>{let release;const fetchImpl=vi.fn().mockImplementationOnce(()=>new Promise(r=>release=r)).mockResolvedValue(response()),h=harness(),{store}=setup(h,fetchImpl);h.change(['content'],{content:'one',plainText:'one'});void store.flush();h.change(['platform'],{platform:'vk'});release(response());await vi.waitFor(()=>expect(fetchImpl).toHaveBeenCalledTimes(2));store.dispose()});
  it('does not enter an immediate retry loop after failure',async()=>{const fetchImpl=vi.fn(async()=>response(false,null,503)),h=harness(),{store}=setup(h,fetchImpl);h.change(['content'],{content:'x',plainText:'x'});await expect(store.flush()).resolves.toBe(false);await Promise.resolve();expect(fetchImpl).toHaveBeenCalledOnce();expect(store.getState()).toMatchObject({savedRevision:0,saveRequested:true});store.dispose()});
  it('retries a failed revision only on a later flush',async()=>{const fetchImpl=vi.fn().mockResolvedValueOnce(response(false)).mockResolvedValue(response()),h=harness(),{store}=setup(h,fetchImpl);h.change(['content'],{content:'x',plainText:'x'});await store.flush();await store.flush();expect(fetchImpl).toHaveBeenCalledTimes(2);store.dispose()});
  it('does not overwrite newer user state during restore',async()=>{let release;const fetchImpl=vi.fn(()=>new Promise(r=>release=r)),h=harness(),{store}=setup(h,fetchImpl),loading=store.load();h.change(['content'],{content:'local',plainText:'local'});release(response(true,{text:'remote',images:[]}));await loading;expect(h.snapshot().content).toBe('local');store.dispose()});
  it('clears runtime and durable image state',async()=>{const h=harness({content:'x',plainText:'x',images:[new File(['x'],'x.jpg')],activePhotoIndex:0,platform:'vk'}),{store,fetchImpl}=setup(h);await store.clear();expect(h.snapshot()).toMatchObject({content:'',images:[],platform:'telegram'});expect(fetchImpl.mock.calls[0][1].body.get('imagesChanged')).toBe('1');store.dispose()});
  it('has no knowledge of UI selectors or mutation/click transport',()=>{const code=source('draft-store.js')+source('drafts.js');for(const forbidden of ["querySelector('.active","querySelector('.platform-tab","querySelector('#previews",'MutationObserver'])expect(code).not.toContain(forbidden);expect(code).not.toMatch(/addEventListener\(['"]click/);expect(code).toContain('state.subscribe(onChange)')});
});

describe('ComposerState composition',()=>{
  it('delegates content and images instead of copying them',()=>{document.body.innerHTML='<textarea id="text"></textarea><input id="image" type="file">';const image=new File(['x'],'x.jpg');window.CosmoComposerImages={getFiles:()=>[image],replaceFiles:vi.fn()};window.CosmoRichEditor={draftValue:()=>`rich:${document.querySelector('#text').value}`,restoreDraft:vi.fn(()=>false),restorePlain:vi.fn(),clear:vi.fn()};window.eval(source('composer-state.js'));const state=window.CosmoComposerStateFactory.create();expect(state.getSnapshot()).toMatchObject({content:'rich:',images:[image],activePhotoIndex:0,platform:'telegram'});state.dispose()});
  it('clamps an oversized restored active photo index',()=>{document.body.innerHTML='<textarea id="text"></textarea><input id="image" type="file">';const files=[new File(['a'],'a.jpg'),new File(['b'],'b.jpg')],manager={getFiles:()=>files,replaceFiles:vi.fn()};const state=window.CosmoComposerStateFactory.create({getImageManager:()=>manager});state.restore({images:files,activePhotoIndex:20});expect(state.getSnapshot().activePhotoIndex).toBe(1);state.dispose()});
  it('restores active photo zero when there are no images',()=>{document.body.innerHTML='<textarea id="text"></textarea><input id="image" type="file">';const manager={getFiles:()=>[],replaceFiles:vi.fn()};const state=window.CosmoComposerStateFactory.create({getImageManager:()=>manager});state.restore({images:[],activePhotoIndex:4});expect(state.getSnapshot().activePhotoIndex).toBe(0);state.dispose()});
  it('clamps the active photo when the image set shrinks',()=>{document.body.innerHTML='<textarea id="text"></textarea><input id="image" type="file">';let files=[new File(['a'],'a.jpg'),new File(['b'],'b.jpg'),new File(['c'],'c.jpg')];const manager={getFiles:()=>files,replaceFiles:value=>{files=value}};const input=document.querySelector('#image'),state=window.CosmoComposerStateFactory.create({imageInput:input,getImageManager:()=>manager});state.setActivePhotoIndex(2);files=files.slice(0,1);input.dispatchEvent(new Event('change'));expect(state.getSnapshot().activePhotoIndex).toBe(0);state.dispose()});
  it('uses ComposerState as the only persistent active-photo owner in app.js',()=>{const app=source('app.js');expect(app).not.toMatch(/\b(?:let|var)\s+[^;]*activePhotoIndex/);expect(app).toContain('CosmoComposerState?.setActivePhotoIndex(index)');expect(app).toContain('CosmoComposerState?.getSnapshot().activePhotoIndex')});
  it('treats the restore event only as a render notification',()=>{const app=source('app.js');expect(app).toContain("addEventListener('cosmo-composer-restore',()=>");expect(app).toContain('renderPhoto(activePhoto(),false)');expect(app).not.toMatch(/cosmo-composer-restore[^;]+setActivePhotoIndex/)});
  it('loads each stateful module once through bootstrap',()=>{const code=source('bootstrap.js');for(const name of ['composer-state.js','draft-store.js','drafts.js'])expect(code.match(new RegExp(name.replace('.','\\.'),'g'))).toHaveLength(1);expect(code.indexOf('composer-state.js')).toBeLessThan(code.indexOf('draft-store.js'));expect(code.indexOf('draft-store.js')).toBeLessThan(code.indexOf('drafts.js'))});
});
