import type {Platform,PublicationResult} from '../../shared/contracts';import {AppError,type Env} from './types';import {validatePublish} from './validation';import {detail,findOrCreate,finish,history,list,pending,publication} from './services/posts';import {getImage,storeImage} from './services/images';import {publishPlatform} from './services/publisher';import {testVKAuthorizationCode} from './services/vk-auth-debug';
const json=(body:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const VK_AUTH_DEBUG_PATH='/api/debug/vk-auth-test',VK_AUTH_DEBUG_ORIGIN='https://buropotok.github.io';
function cors(req:Request,env:Env):Record<string,string>{const origin=req.headers.get('origin'),isExtension=origin===env.ALLOWED_EXTENSION_ORIGIN,isDebugPage=new URL(req.url).pathname===VK_AUTH_DEBUG_PATH&&origin===VK_AUTH_DEBUG_ORIGIN;return origin&&(isExtension||isDebugPage)?{'access-control-allow-origin':origin,'access-control-allow-headers':'authorization, content-type','access-control-allow-methods':'GET, POST, OPTIONS','vary':'Origin'}:{}}
function authorized(req:Request,env:Env){const supplied=req.headers.get('authorization')?.replace(/^Bearer\s+/,'')??'';return !!env.PUBLISH_API_TOKEN&&supplied===env.PUBLISH_API_TOKEN}
async function route(req:Request,env:Env){const u=new URL(req.url),headers=cors(req,env);if(req.method==='OPTIONS')return Object.keys(headers).length?new Response(null,{status:204,headers}):new Response(null,{status:403});
 if(req.method==='GET'&&u.pathname==='/history.txt')return new Response(await history(env),{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=60'}});
 if(req.method==='GET'&&u.pathname==='/api/posts')return json(await list(env,u,u.origin),200,headers);
 const postMatch=u.pathname.match(/^\/api\/posts\/(\d+)$/);if(req.method==='GET'&&postMatch){const p=await detail(env,Number(postMatch[1]),u.origin);return p?json(p,200,headers):json({error:{code:'NOT_FOUND',message:'Публикация не найдена'}},404,headers)}
 const imageMatch=u.pathname.match(/^\/api\/images\/(.+)$/);if(req.method==='GET'&&imageMatch){const object=await getImage(env,decodeURIComponent(imageMatch[1]));if(!object)return new Response('Not found',{status:404});const h=new Headers();object.writeHttpMetadata(h);h.set('etag',object.httpEtag);h.set('cache-control','public, max-age=86400');return new Response(object.body,{headers:h})}
 if(req.method==='POST'&&u.pathname===VK_AUTH_DEBUG_PATH){let body:unknown;try{body=await req.json()}catch{throw new AppError('INVALID_JSON','Некорректный JSON payload',400)}if(!body||typeof body!=='object')throw new AppError('INVALID_REQUEST','JSON object обязателен',400);const input=body as Record<string,unknown>,code=typeof input.code==='string'?input.code.trim():'',deviceId=typeof input.device_id==='string'?input.device_id.trim():'',codeVerifier=typeof input.code_verifier==='string'?input.code_verifier:'',state=typeof input.state==='string'?input.state:'',groupId=typeof input.group_id==='number'?input.group_id:Number(input.group_id);if(!code||code.length>2048)throw new AppError('INVALID_REQUEST','Поле code обязательно',400);if(!deviceId||deviceId.length>2048)throw new AppError('INVALID_REQUEST','Поле device_id обязательно',400);if(!/^[A-Za-z0-9_-]{43,128}$/.test(codeVerifier))throw new AppError('INVALID_REQUEST','Поле code_verifier некорректно',400);if(!/^[A-Za-z0-9_-]{32,128}$/.test(state))throw new AppError('INVALID_REQUEST','Поле state некорректно',400);if(!Number.isSafeInteger(groupId)||groupId<=0)throw new AppError('INVALID_REQUEST','Поле group_id должно быть положительным целым числом',400);const result=await testVKAuthorizationCode({code,deviceId,codeVerifier,state,groupId});return json(result,'transport_error'in result?502:200,headers)}
 if(req.method==='POST'&&u.pathname==='/api/publish'){if(!authorized(req,env))throw new AppError('UNAUTHORIZED','Неверный personal API token',401);const form=await req.formData();const raw=form.get('payload');if(typeof raw!=='string')throw new AppError('INVALID_REQUEST','Поле payload обязательно',400);let parsed:unknown;try{parsed=JSON.parse(raw)}catch{throw new AppError('INVALID_JSON','Некорректный JSON payload',400)}const input=validatePublish(parsed);const file=form.get('image');if(file!==null&&!(file instanceof File))throw new AppError('INVALID_IMAGE','Некорректное изображение',400);
  const postId=await findOrCreate(env,input.idempotency_key,input.text,input.metadata);if(file)await storeImage(env,postId,file);const results:Partial<Record<Platform,PublicationResult>>={};
  for(const platform of input.targets){const old=await publication(env,postId,platform);if(old?.status==='published'){results[platform]={status:'published',external_id:old.external_post_id,url:old.external_url,...(platform==='vk'&&file?{image_status:'manual_required' as const}:{})};continue}await pending(env,postId,platform);try{const result=await publishPlatform(env,platform,input.text,file??undefined);results[platform]={status:'published',...result}}catch(e){console.error(`${platform} publication failed`,e instanceof AppError?e.code:e);results[platform]={status:'failed',error:e instanceof Error?e.message:'Неизвестная ошибка'}}await finish(env,postId,platform,results[platform]!)}return json({post_id:postId,publications:results},200,headers)}
 throw new AppError('NOT_FOUND','Маршрут не найден',404)}
export default{async fetch(req:Request,env:Env){try{return await route(req,env)}catch(e){const err=e instanceof AppError?e:new AppError('INTERNAL_ERROR','Внутренняя ошибка сервера');if(!(e instanceof AppError))console.error(e);return json({error:{code:err.code,message:err.message}},err.status,cors(req,env))}}};
