export const vkMiniAppHtml = `<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Публикация VK</title>
  <script src="https://unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js"></script>
  <style>body{font-family:sans-serif;padding:24px}button{width:100%;padding:16px;font-size:18px}pre{margin-top:20px;white-space:pre-wrap;word-break:break-word;font-size:12px}</style>
</head><body><h2>Публикация в VK</h2><button id="post" disabled>Открыть публикацию</button><pre id="status">Загружаем публикацию…</pre>
<script>
const VK_APP_ID=54742217,VK_API_VERSION='5.199',status=document.getElementById('status'),button=document.getElementById('post');let handoff=null,currentToken='',logs=[],started=performance.now();
function elapsed(){return((performance.now()-started)/1000).toFixed(2)+'s'}
function clean(value){if(value==null)return value;if(typeof value==='string'){if(value.length>600)return value.slice(0,600)+'…';return value.replace(/access_token=[^&\s]+/gi,'access_token=***')}if(Array.isArray(value))return value.map(clean);if(typeof value==='object'){const out={};for(const[k,v]of Object.entries(value)){if(/token/i.test(k))out[k]='***';else if(k==='upload_url'||k==='uploadUrl'){try{const u=new URL(String(v));out[k]=u.origin+u.pathname}catch{out[k]=String(v)}}else out[k]=clean(v)}return out}return value}
function log(label,data){const line='['+elapsed()+'] '+label+(data===undefined?'':' | '+JSON.stringify(clean(data)));logs.push(line);status.textContent=logs.join('\n');console.log(label,clean(data))}
function handoffToken(){const query=new URLSearchParams(location.search).get('handoff');if(query)return query;const hash=new URLSearchParams(location.hash.replace(/^#/, '')).get('handoff');if(hash)return hash;const launch=new URLSearchParams(location.search).get('vk_ref')||'';const match=launch.match(/(?:^|[?&#])handoff=([A-Za-z0-9_-]+)/);return match?match[1]:''}
function vkError(stage,error){const data=error&&typeof error==='object'?error:{},nested=data.error_data&&typeof data.error_data==='object'?data.error_data:{},api=nested.api_error&&typeof nested.api_error==='object'?nested.api_error:{},code=api.error_code||nested.error_code||data.error_code||'',message=api.error_msg||nested.error_reason||nested.error_msg||data.message||(error instanceof Error?error.message:'')||data.error_type||'Неизвестная ошибка',parts=['Этап: '+stage];if(data.error_type)parts.push('Тип: '+data.error_type);if(code!=='')parts.push('Код: '+code);parts.push('Сообщение: '+message);return parts.join('\n')}
async function bridge(name,payload){log('→ Bridge '+name,payload);try{const r=await vkBridge.send(name,payload);log('← Bridge '+name,r);return r}catch(e){log('← Bridge '+name+' ERROR',e);throw e}}
async function callVkApi(method,params){log('→ VK API '+method,params);try{const result=await bridge('VKWebAppCallAPIMethod',{method,params:{...params,v:VK_API_VERSION}});log('← VK API '+method,result);if(result?.response===undefined)throw new Error('VK API не вернул результат');return result.response}catch(error){throw new Error(vkError(method,error))}}
async function prepareNativePhotoAttachment(){log('Начало подготовки фото',{groupId:handoff.groupId,imageUrl:handoff.imageUrl});let auth;try{auth=await bridge('VKWebAppGetAuthToken',{app_id:VK_APP_ID,scope:'photos'})}catch(error){throw new Error(vkError('VKWebAppGetAuthToken (photos)',error))}if(!auth?.access_token)throw new Error('VK не предоставил access_token');log('Auth token получен',{hasAccessToken:true,expiresIn:auth.expires_in||null});const server=await callVkApi('photos.getWallUploadServer',{access_token:auth.access_token,group_id:handoff.groupId});if(!server?.upload_url)throw new Error('photos.getWallUploadServer: нет upload_url');let host='';try{host=new URL(server.upload_url).hostname}catch{}log('Upload server получен',{host,uploadUrl:server.upload_url});let uploadResponse,raw='';log('→ Worker /api/vk-handoff-upload',{method:'POST',host});try{uploadResponse=await fetch('/api/vk-handoff-upload/'+encodeURIComponent(currentToken),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({uploadUrl:server.upload_url})});raw=await uploadResponse.text();log('← Worker /api/vk-handoff-upload',{status:uploadResponse.status,statusText:uploadResponse.statusText,contentType:uploadResponse.headers.get('content-type'),body:raw})}catch(error){log('← Worker /api/vk-handoff-upload NETWORK ERROR',{name:error?.name,message:error?.message});throw new Error('upload image to VK: '+(error instanceof Error?error.message:String(error)))}let uploaded=null;try{uploaded=raw?JSON.parse(raw):null}catch{}if(!uploadResponse.ok)throw new Error('upload image to VK: '+(uploaded?.error?.message||'HTTP '+uploadResponse.status)+'; raw='+raw.slice(0,500));if(!uploaded?.photo||uploaded?.server===undefined||!uploaded?.hash)throw new Error('upload image to VK: неполный ответ; raw='+raw.slice(0,500));log('Upload VK принят',{photo:uploaded.photo,server:uploaded.server,hash:uploaded.hash});const saved=await callVkApi('photos.saveWallPhoto',{access_token:auth.access_token,group_id:handoff.groupId,photo:uploaded.photo,server:uploaded.server,hash:uploaded.hash});log('photos.saveWallPhoto result',saved);const photo=Array.isArray(saved)?saved[0]:null;if(!photo?.owner_id||!photo?.id)throw new Error('photos.saveWallPhoto: VK не вернул сохранённую фотографию');const attachment='photo'+photo.owner_id+'_'+photo.id+(photo.access_key?'_'+photo.access_key:'');log('Attachment готов',{attachment});return attachment}
async function init(){try{log('Mini App init start',{href:location.href});await bridge('VKWebAppInit');currentToken=handoffToken();log('Handoff token',{present:!!currentToken,length:currentToken.length});if(!currentToken)throw new Error('Не получен handoff token');log('→ GET /api/vk-handoff');const response=await fetch('/api/vk-handoff/'+encodeURIComponent(currentToken),{cache:'no-store'}),raw=await response.text();log('← GET /api/vk-handoff',{status:response.status,contentType:response.headers.get('content-type'),body:raw});let result=null;try{result=raw?JSON.parse(raw):null}catch{}if(!response.ok)throw new Error(result?.error?.message||'Не удалось загрузить публикацию.');handoff=result;button.disabled=false;log('Публикация готова',{groupId:handoff.groupId,hasImage:!!handoff.imageUrl,textLength:(handoff.text||'').length})}catch(error){log('INIT ERROR',{message:error instanceof Error?error.message:String(error)})}}
button.addEventListener('click',async()=>{if(!handoff)return;button.disabled=true;try{log('Нажата публикация');let attachment='';if(handoff.imageUrl)attachment=await prepareNativePhotoAttachment();const params={owner_id:-handoff.groupId,message:handoff.text};if(attachment)params.attachments=attachment;log('→ VKWebAppShowWallPostBox',params);let result;try{result=await bridge('VKWebAppShowWallPostBox',params)}catch(error){throw new Error(vkError('VKWebAppShowWallPostBox',error))}log('← Публикация завершена',result)}catch(error){log('ERROR',{message:error instanceof Error?error.message:String(error)})}finally{button.disabled=false}});init();
</script></body></html>`;
