import {plainTextToDocument,safeLink,type InlineMark,type PostBlock,type PostButton,type PostDocument,type TextRun} from '../../../shared/post-document';
const BLOCK=new Set(['P','DIV','H1','H2','H3','H4','H5','H6','PRE','BLOCKQUOTE']);
const DETAILS_MARKER='в telegram текст будет раскрываемым',BUTTON_MARKER='в telegram будет отображаться в виде кнопки';
export function normalizeText(text:string){return text.replace(/\u00a0/g,' ').replace(/[ \t]+\n/g,'\n').replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function cleanClone(root:Element){const clone=root.cloneNode(true) as Element;clone.querySelectorAll('button,svg,script,style,[data-social-publisher],[aria-hidden="true"],sup a').forEach(x=>x.remove());return clone}
export function parseResponseText(root:Element){const clone=cleanClone(root);const walk=(node:Node):string=>{if(node.nodeType===Node.TEXT_NODE)return node.textContent??'';if(!(node instanceof Element))return '';const tag=node.tagName;if(tag==='BR')return '\n';let value=[...node.childNodes].map(walk).join('');if(tag==='LI'){const parent=node.parentElement;const n=parent?.tagName==='OL'?[...parent.children].filter(x=>x.tagName==='LI').indexOf(node)+1:null;value=`${n?`${n}.`:'•'} ${value.trim()}\n`}else if(BLOCK.has(tag))value=`${value.trim()}\n\n`;else if(tag==='A'&&node.getAttribute('href')&&!value.trim())value=node.getAttribute('href')!;return value};return normalizeText(walk(clone))}
export const parseResponse=parseResponseText;
export function hasFiveChoices(text:string){return [1,2,3,4,5].every(n=>new RegExp(`(?:^|\\n)\\s*${n}[.)]\\s+\\S`,'m').test(text))}
function marker(text:string,expected:string){return normalizeText(text).toLocaleLowerCase('ru-RU').replace(/[()*.!,:;]+/g,' ').replace(/\s+/g,' ').trim()===expected}
function equalMarks(a:InlineMark[]|undefined,b:InlineMark[]|undefined){return JSON.stringify(a??[])===JSON.stringify(b??[])}
function compact(runs:TextRun[]){const out:TextRun[]=[];for(const run of runs){if(!run.text)continue;const last=out.at(-1);if(last&&equalMarks(last.marks,run.marks))last.text+=run.text;else out.push(run)}return out}
export function parseInlineRuns(node:Node,marks:InlineMark[]=[]):TextRun[]{if(node.nodeType===Node.TEXT_NODE)return node.textContent?[{text:node.textContent,marks:marks.length?[...marks]:undefined}]:[];if(!(node instanceof Element))return[];const tag=node.tagName;if(tag==='BR')return[{text:'\n',marks:marks.length?[...marks]:undefined}];let next=[...marks];if(tag==='STRONG'||tag==='B')next.push({type:'bold'});else if(tag==='EM'||tag==='I')next.push({type:'italic'});else if(tag==='S'||tag==='DEL')next.push({type:'strikethrough'});else if(tag==='A'){const href=node.getAttribute('href'),url=href&&safeLink(href);if(url)next.push({type:'link',href:url})}return compact([...node.childNodes].flatMap(child=>parseInlineRuns(child,next)))}
function directListChildren(element:Element){return [...element.children].filter(child=>child.tagName==='LI')}
function listLine(item:Element,depth:number,ordered:boolean,index:number){const clone=item.cloneNode(true) as Element;clone.querySelectorAll(':scope > ul,:scope > ol').forEach(n=>n.remove());const prefix=ordered?`${index+1}.`:'•',line=`${'  '.repeat(depth)}${prefix} `;const runs=[{text:line},...parseInlineRuns(clone)];const nested=[...item.children].filter(child=>child.tagName==='UL'||child.tagName==='OL').flatMap(child=>flattenList(child,depth+1));return [...runs,...(nested.length?[{text:'\n'},...nested]:[])]}
function flattenList(list:Element,depth=0):TextRun[]{const ordered=list.tagName==='OL';return directListChildren(list).flatMap((item,index)=>index?[{text:'\n'},...listLine(item,depth,ordered,index)]:listLine(item,depth,ordered,index))}
function parseList(list:Element):PostBlock{const ordered=list.tagName==='OL',items=directListChildren(list).map(item=>{const clone=item.cloneNode(true) as Element;clone.querySelectorAll(':scope > ul,:scope > ol').forEach(node=>node.remove());const own=parseInlineRuns(clone),nested=[...item.children].filter(child=>child.tagName==='UL'||child.tagName==='OL').flatMap(child=>flattenList(child,1));return compact([...own,...(nested.length?[{text:'\n'},...nested]:[])])});return {type:ordered?'ordered_list':'bullet_list',items}}
function quoteRuns(quote:Element){const parts=[...quote.children].length?[...quote.children]:[quote];return compact(parts.flatMap((part,index)=>index?[{text:'\n'},...(part.tagName==='UL'||part.tagName==='OL'?flattenList(part):parseInlineRuns(part))]:(part.tagName==='UL'||part.tagName==='OL'?flattenList(part):parseInlineRuns(part))))}
function meaningfulChildren(root:Element):Element[]{return [...root.children].flatMap(child=>{const meaningful=normalizeText(child.textContent??'')||['UL','OL','BLOCKQUOTE'].includes(child.tagName);if(!meaningful)return[];const transparent=['DIV','SECTION','ARTICLE'].includes(child.tagName)&&[...child.children].some(n=>/^(H[1-6]|P|BLOCKQUOTE|UL|OL)$/.test(n.tagName));return transparent?meaningfulChildren(child):[child]})}
function extractButton(elements:Element[],index:number):{button?:PostButton;consume:number;fallback?:TextRun[]}|null{const element=elements[index],internal=[...element.querySelectorAll('em,i')].some(node=>marker(node.textContent??'',BUTTON_MARKER)),next=elements[index+1],external=!!next&&marker(normalizeText(next.textContent??''),BUTTON_MARKER);if(!internal&&!external)return null;const links=[...element.querySelectorAll<HTMLAnchorElement>('a[href]')];if(element.matches('a[href]'))links.unshift(element as HTMLAnchorElement);const consume=external?2:1;if(links.length!==1)return {consume,fallback:parseInlineRuns(element).filter(run=>!marker(run.text,BUTTON_MARKER))};const url=safeLink(links[0].getAttribute('href')??''),text=normalizeText(links[0].textContent??'');return url&&text?{button:{text,url},consume}:{consume,fallback:[{text}]}}

export function parsePostDocumentFromResponse(root:Element):PostDocument{try{const clean=cleanClone(root),elements=meaningfulChildren(clean),blocks:PostBlock[]=[],buttons:PostButton[]=[];for(let index=0;index<elements.length;){const element=elements[index],tag=element.tagName,button=extractButton(elements,index);if(button){if(button.button)buttons.push(button.button);else if(button.fallback?.length)blocks.push({type:'paragraph',content:button.fallback});index+=button.consume;continue}if(/^H[1-6]$/.test(tag)){const text=normalizeText(element.textContent??''),internalMarker=marker(text.replace(/^(.*?)\(?в telegram/iu,'в telegram'),DETAILS_MARKER)||[...element.querySelectorAll('em,i')].some(node=>marker(node.textContent??'',DETAILS_MARKER)),annotation=elements[index+1],adjacentMarker=!!annotation&&marker(annotation.textContent??'',DETAILS_MARKER),quote=elements[index+(adjacentMarker?2:1)];if((internalMarker||adjacentMarker)&&quote?.tagName==='BLOCKQUOTE'){const titleText=normalizeText([...element.childNodes].filter(node=>!(node instanceof Element&&['EM','I'].includes(node.tagName))).map(node=>node.textContent??'').join('')).replace(/[()]+$/g,'').trim()||'Подробнее';blocks.push({type:'details',title:[{text:titleText}],content:quoteRuns(quote)});index+=adjacentMarker?3:2;continue}blocks.push({type:'heading',content:parseInlineRuns(element).filter(run=>!marker(run.text,DETAILS_MARKER))});index++;continue}if(marker(element.textContent??'',DETAILS_MARKER)){index++;continue}if(tag==='UL'||tag==='OL')blocks.push(parseList(element));else if(tag==='BLOCKQUOTE')blocks.push({type:'quote',content:quoteRuns(element)});else blocks.push({type:'paragraph',content:parseInlineRuns(element)});index++}const document:PostDocument={schemaVersion:1,blocks:blocks.length?blocks:buttons.length?[{type:'paragraph',content:[]}]:plainTextToDocument(parseResponseText(root)).blocks,...(buttons.length?{buttons}:{})};return document}catch{return plainTextToDocument(parseResponseText(root))}}
