import {describe,expect,it,beforeEach} from 'vitest';import {JSDOM} from 'jsdom';import {hasFiveChoices,normalizeText,parseInlineRuns,parsePostDocumentFromResponse,parseResponseText} from './response-parser';
function root(html:string){const dom=new JSDOM(`<div>${html}</div>`,{url:'https://chatgpt.com/'});Object.assign(globalThis,{Node:dom.window.Node,Element:dom.window.Element});return dom.window.document.body.firstElementChild!}
beforeEach(()=>root(''));
describe('plain response parser',()=>{it('normalizes blocks and removes owned UI',()=>{const element=root('<h2>Заголовок</h2><p>Текст <strong>важный</strong></p><ol><li>Один</li><li>Два</li></ol><section data-social-publisher="telegram-preview">Preview</section>');expect(parseResponseText(element)).toBe('Заголовок\n\nТекст важный\n\n1. Один\n2. Два')});it('detects exactly present five choices',()=>expect(hasFiveChoices('1. a\n2. b\n3. c\n4. d\n5. e')).toBe(true));it('cleans whitespace',()=>expect(normalizeText(' a  \n\n\n b ')).toBe('a\n\nb'))});
describe('semantic DOM importer',()=>{
 it('imports headings and inline mark combinations',()=>{const document=parsePostDocumentFromResponse(root('<h3>Заголовок</h3><p><strong>bold <em>bold italic</em></strong> <i>italic</i> <del>strike</del></p>'));expect(document.blocks[0]).toEqual({type:'heading',content:[{text:'Заголовок'}]});expect(document.blocks[1]).toEqual({type:'paragraph',content:[{text:'bold ',marks:[{type:'bold'}]},{text:'bold italic',marks:[{type:'bold'},{type:'italic'}]},{text:' '},{text:'italic',marks:[{type:'italic'}]},{text:' '},{text:'strike',marks:[{type:'strikethrough'}]}]})});
 it('keeps ordinary safe links and degrades unsafe links to text',()=>{const document=parsePostDocumentFromResponse(root('<p><a href="https://example.com">Safe</a> <a href="javascript:alert(1)">Unsafe</a></p>'));expect((document.blocks[0] as any).content).toEqual([{text:'Safe',marks:[{type:'link',href:'https://example.com/'}]},{text:' Unsafe'}])});
 it('imports quotes and bullet/ordered lists',()=>{const document=parsePostDocumentFromResponse(root('<blockquote><p>Цитата</p></blockquote><ul><li>А</li><li>Б</li></ul><ol><li>Раз</li><li>Два</li></ol>'));expect(document.blocks.map(block=>block.type)).toEqual(['quote','bullet_list','ordered_list']);expect((document.blocks[2] as any).items).toEqual([[{text:'Раз'}],[{text:'Два'}]])});
 it('preserves nested and mixed list indentation deterministically',()=>{const document=parsePostDocumentFromResponse(root('<ul><li>Root<ul><li>Child<ol><li>Deep</li></ol></li></ul></li></ul>'));expect((document.blocks[0] as any).items[0].map((run:any)=>run.text).join('')).toBe('Root\n  • Child\n    1. Deep')});
 it.each(['Подробнее <em>(в Telegram текст будет раскрываемым)</em>','Подробнее <i> (В TELEGRAM   текст будет раскрываемым!) </i>'])('imports contextual details and removes its marker: %s',heading=>{const document=parsePostDocumentFromResponse(root(`<h4>${heading}</h4><blockquote><p>Текст</p><ul><li>Пункт</li></ul></blockquote>`));expect(document.blocks).toHaveLength(1);expect(document.blocks[0]).toMatchObject({type:'details',title:[{text:'Подробнее'}]});expect((document.blocks[0] as any).content.map((run:any)=>run.text).join('')).toBe('Текст\n• Пункт');expect(JSON.stringify(document)).not.toContain('раскрываемым')});
 it('imports a separately rendered details annotation and removes it',()=>{const document=parsePostDocumentFromResponse(root('<h4>Подробнее</h4><p><em>(в Telegram текст будет раскрываемым)</em></p><blockquote><p>Скрытый текст</p></blockquote>'));expect(document.blocks).toEqual([{type:'details',title:[{text:'Подробнее'}],content:[{text:'Скрытый текст'}]}]);expect(JSON.stringify(document)).not.toContain('раскрываемым')});
 it('does not treat a plain Подробнее heading as details',()=>expect(parsePostDocumentFromResponse(root('<h4>Подробнее</h4><blockquote>Текст</blockquote>')).blocks.map(block=>block.type)).toEqual(['heading','quote']));
 it('falls back safely when a details marker has no blockquote',()=>{const document=parsePostDocumentFromResponse(root('<h4>Подробнее <em>(в Telegram текст будет раскрываемым)</em></h4><p>Текст</p>'));expect(document.blocks.map(block=>block.type)).toEqual(['heading','paragraph']);expect(JSON.stringify(document)).not.toContain('раскрываемым')});
 it('removes a standalone details annotation even without a valid pair',()=>{const document=parsePostDocumentFromResponse(root('<h4>Подробнее</h4><p><em>(в Telegram текст будет раскрываемым)</em></p><p>Текст</p>'));expect(document.blocks.map(block=>block.type)).toEqual(['heading','paragraph']);expect(JSON.stringify(document)).not.toContain('раскрываемым')});
 it('converts a marked CTA into one button without an inline duplicate',()=>{const document=parsePostDocumentFromResponse(root('<p><a href="https://example.com">Записаться</a> <em>(в Telegram будет отображаться в виде кнопки)</em></p>'));expect(document.buttons).toEqual([{text:'Записаться',url:'https://example.com/'}]);expect(document.blocks).toEqual([{type:'paragraph',content:[]}])});
 it('supports an adjacent button marker and preserves unsafe CTA text',()=>{const safe=parsePostDocumentFromResponse(root('<p><a href="https://example.com/a">A</a></p><p><em>(в Telegram будет отображаться в виде кнопки)</em></p><p><a href="https://example.com/b">B</a></p><p><em>(в Telegram будет отображаться в виде кнопки)</em></p>'));expect(safe.buttons).toHaveLength(2);const unsafe=parsePostDocumentFromResponse(root('<p><a href="data:text/plain,x">CTA</a></p><p><em>(в Telegram будет отображаться в виде кнопки)</em></p>'));expect(unsafe.buttons).toBeUndefined();expect(JSON.stringify(unsafe)).toContain('CTA');expect(JSON.stringify(unsafe)).not.toContain('кнопки')});
 it('ignores extension-owned preview DOM',()=>{const document=parsePostDocumentFromResponse(root('<h3>Пост</h3><section data-social-publisher="telegram-preview"><h3>Не импортировать</h3></section>'));expect(document.blocks).toEqual([{type:'heading',content:[{text:'Пост'}]}])});
});
