import {post,posts,publish} from '../api/client';import type {Platform,PublicationResult,PostSummary} from '../../../shared/contracts';
interface PublisherDraft {text?:string;images?:string[]}
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;let image:Blob|undefined,postId:number|undefined,key=crypto.randomUUID(),last:Partial<Record<Platform,PublicationResult>>={};
function show(tab:string){document.querySelectorAll('main>section').forEach(s=>(s as HTMLElement).hidden=s.id!==tab);if(tab==='history')void loadHistory()}
document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab!));
async function blobFromUrl(url:string){const r=await fetch(url);if(!r.ok)throw new Error('Изображение ChatGPT недоступно; загрузите его вручную');return r.blob()}
function preview(blob?:Blob){image=blob;const img=$<HTMLImageElement>('preview');if(blob){img.src=URL.createObjectURL(blob);img.hidden=false}else{img.hidden=true;img.removeAttribute('src')}}
function renderDraft(draft:PublisherDraft){$<HTMLTextAreaElement>('text').value=draft.text??'';const box=$('detected');box.replaceChildren();for(const url of draft.images??[]){const img=document.createElement('img');img.src=url;img.className='candidate';img.title='Выбрать изображение';img.onclick=async()=>{try{preview(await blobFromUrl(url));box.querySelectorAll('img').forEach(x=>x.classList.remove('selected'));img.classList.add('selected')}catch(e){alert(String(e))}};box.append(img)}}
async function draft(){const {draft}=await chrome.storage.session.get('draft');if(draft)renderDraft(draft)}
chrome.runtime.onMessage.addListener((message:unknown)=>{if(typeof message==='object'&&message!==null&&(message as {type?:unknown}).type==='DRAFT_UPDATED')renderDraft((message as {draft:PublisherDraft}).draft)});
$<HTMLInputElement>('upload').onchange=e=>preview((e.target as HTMLInputElement).files?.[0]);$('removeImage').onclick=()=>preview();
function renderResults(results:Partial<Record<Platform,PublicationResult>>){last={...last,...results};$('results').innerHTML=(['vk','telegram'] as Platform[]).filter(p=>last[p]).map(p=>`<div class="result ${last[p]!.status==='published'?'ok':'fail'}">${p.toUpperCase()}: ${last[p]!.status==='published'?'✓ Опубликовано':'✗ '+(last[p]!.error??'Ошибка')}</div>`).join('')}
$('publish').onclick=async()=>{const targets=(['vk','telegram'] as Platform[]).filter(p=>( $(p) as HTMLInputElement).checked&&last[p]?.status!=='published');if(!targets.length)return alert('Выберите площадку или нет неуспешных площадок');const text=$<HTMLTextAreaElement>('text').value.trim(),firstLine=text.split('\n').find(Boolean)?.replace(/^#+\s*/,'').slice(0,120)??'';const metadata={title:firstLine,topic:firstLine,summary:text.replace(/\s+/g,' ').slice(0,240),content_type:'freeform'};const b=$<HTMLButtonElement>('publish');b.disabled=true;b.textContent='Публикуем…';try{const r=await publish({text,targets,metadata,postId,image,idempotencyKey:key});postId=r.post_id;renderResults(r.publications)}catch(e){$('results').textContent=e instanceof Error?e.message:String(e)}finally{b.disabled=false;b.textContent='Опубликовать'}};
function statuses(p:PostSummary){return (['vk','telegram'] as Platform[]).map(x=>`${x.toUpperCase()} ${p.publications[x]?.status==='published'?'✓':p.publications[x]?'✗':'—'}`).join(' · ')}
async function loadHistory(){try{const r=await posts($<HTMLInputElement>('search').value);$('cards').innerHTML=r.items.map(p=>`<div class="card" data-id="${p.id}">${p.image_url?`<img src="${p.image_url}">`:''}<b>${p.title||p.topic||'Публикация'}</b><div>${new Date(p.published_at||p.created_at).toLocaleDateString('ru-RU')}</div><p>${p.summary||p.text.slice(0,130)}</p><small>${statuses(p)}</small><div style="clear:both"></div></div>`).join('')||'<p>Публикаций нет.</p>';document.querySelectorAll<HTMLElement>('.card').forEach(c=>c.onclick=()=>void detail(Number(c.dataset.id)))}catch(e){$('cards').textContent=String(e)}}
async function detail(id:number){const p=await post(id);$('detail').innerHTML=`<h2>${p.title||p.topic||'Публикация'}</h2>${p.image_url?`<img src="${p.image_url}">`:''}<p>${p.text.replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]!))}</p><p>${statuses(p)}</p>`}
$('searchButton').onclick=()=>void loadHistory();$('save').onclick=async()=>{await chrome.storage.local.set({workerBaseUrl:$<HTMLInputElement>('workerUrl').value.trim(),apiToken:$<HTMLInputElement>('apiToken').value});alert('Сохранено')};chrome.storage.local.get(['workerBaseUrl','apiToken']).then((s:{workerBaseUrl?:string;apiToken?:string})=>{$<HTMLInputElement>('workerUrl').value=s.workerBaseUrl??'';$<HTMLInputElement>('apiToken').value=s.apiToken??''});void draft();
