import {ApiError} from '../api/auth';import {createTelegramPairing,disconnectTelegram,post,posts,protectedImage,publish,telegramConnection,type TelegramConnection} from '../api/client';import type {Platform,PublicationResult,PostSummary} from '../../../shared/contracts';
import type {PublisherDraft} from '../publisher/draft';
import {extensionVersionLabel} from './version';
import {BeforeAfterEditor} from './before-after/editor';
import {downloadComposedImage} from './before-after/export';
import {PostEditor} from './post-editor';
import {hasTelegramSpecificFormatting, plainTextToDocument, type PostDocument} from '../../../shared/post-document';
import {planTelegramPublication,renderTelegram, type TelegramBlock,type TelegramSegment} from '../../../shared/telegram-renderer';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;let image:Blob|undefined,previewUrl:string|undefined,postId:number|undefined,key=crypto.randomUUID(),last:Partial<Record<Platform,PublicationResult>>={};
let beforeAfter:BeforeAfterEditor;
let editor:PostEditor;
$('extensionVersion').textContent=extensionVersionLabel();
function appendSegments(parent:HTMLElement,segments:TelegramSegment[]){for(const segment of segments){let node:Node=document.createTextNode(segment.text);for(const mark of segment.marks){const element=document.createElement(mark.type==='bold'?'strong':mark.type==='italic'?'em':mark.type==='underline'?'u':mark.type==='strikethrough'?'s':mark.type==='link'?'a':'span');if(mark.type==='spoiler')element.className='tg-spoiler';if(mark.type==='link'){element.className='tg-link';(element as HTMLAnchorElement).href=mark.href;(element as HTMLAnchorElement).target='_blank';(element as HTMLAnchorElement).rel='noopener noreferrer';}element.append(node);node=element;}parent.append(node);}}
function appendTelegramBlocks(root:HTMLElement,blocks:TelegramBlock[]){blocks.forEach(block=>{if(block.kind==='expandable_quote'){const details=document.createElement('details');details.className='tg-block tg-details';const summary=document.createElement('summary');appendSegments(summary,block.title?.length?block.title:[{text:'Подробнее',marks:[]}]);details.append(summary);const body=document.createElement('div');body.className='tg-details-body';appendSegments(body,block.segments);details.append(body);root.append(details);return}const element=document.createElement('div');element.className=`tg-block ${block.kind==='quote'?'tg-quote':block.source==='heading'?'tg-heading':''}`;if(block.prefix)element.append(document.createTextNode(block.prefix));appendSegments(element,block.segments);root.append(element)})}
function telegramBubble(blocks:TelegramBlock[],withMedia=false,buttons=editor?.document().buttons??[]){const article=document.createElement('article');article.className='telegram-message';if(withMedia&&previewUrl){const media=document.createElement('img');media.src=previewUrl;media.alt='Медиа Telegram';article.append(media)}const root=document.createElement('div');appendTelegramBlocks(root,blocks);article.append(root);if(buttons.length){const keyboard=document.createElement('div');keyboard.className='telegram-buttons';buttons.forEach(button=>{const link=document.createElement('a');link.href=button.url;link.textContent=button.text;link.target='_blank';link.rel='noopener noreferrer';keyboard.append(link)});article.append(keyboard)}const time=document.createElement('time');time.textContent='сейчас ✓';article.append(time);return article}
function renderTelegramPreview(postDocument:PostDocument){const rendered=renderTelegram(postDocument),plan=planTelegramPublication(rendered,!!image),stage=document.querySelector<HTMLElement>('.telegram-stage')!;stage.replaceChildren();if(plan.type==='photo_then_text'){stage.append(telegramBubble([],true),telegramBubble(rendered.blocks));const warning=document.createElement('p');warning.className='telegram-limit-warning';warning.textContent='Текст длиннее подписи Telegram: фото и текст будут опубликованы двумя сообщениями.';stage.prepend(warning)}else stage.append(telegramBubble(rendered.blocks,plan.type==='photo_with_caption'));$('vkWarning').hidden=!hasTelegramSpecificFormatting(postDocument);}
async function persistDocument(document:PostDocument){const stored=await chrome.storage.session.get('draft'),current=(stored.draft??{}) as Partial<PublisherDraft>;await chrome.storage.session.set({draft:{...current,originalText:current.originalText??editor.text(),publicationText:editor.text(),imageMode:current.imageMode??'text_only',image:current.image??null,postDocument:document}});}
editor=new PostEditor($('editor'),undefined,'',document=>{renderTelegramPreview(document);void persistDocument(document)});renderTelegramPreview(editor.document());
document.querySelectorAll<HTMLButtonElement>('[data-mark]').forEach(button=>button.onmousedown=event=>{event.preventDefault();button.classList.toggle('active',editor.applyMark(button.dataset.mark as 'bold'|'italic'|'underline'|'strikethrough'|'spoiler'))});
document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button=>button.onmousedown=event=>{event.preventDefault();const action=button.dataset.action!;if(action==='undo'||action==='redo')editor.history(action);else if(action==='link')editor.link();else if(action==='clear')editor.clear();else if(action==='emoji')editor.emoji();else if(action==='image')$<HTMLInputElement>('upload').click();else if(action==='button')editor.button()});
document.querySelectorAll<HTMLButtonElement>('[data-block]').forEach(button=>button.onmousedown=event=>{event.preventDefault();button.classList.toggle('active',editor.block(button.dataset.block as any));closeMenus()});
function closeMenus(){document.querySelectorAll<HTMLElement>('[data-menu-panel]').forEach(panel=>panel.hidden=true);document.querySelectorAll<HTMLButtonElement>('[data-menu]').forEach(button=>button.setAttribute('aria-expanded','false'))}
document.querySelectorAll<HTMLButtonElement>('[data-menu]').forEach(button=>{button.onmousedown=event=>event.preventDefault();button.onclick=event=>{event.stopPropagation();const panel=document.querySelector<HTMLElement>(`[data-menu-panel="${button.dataset.menu}"]`)!;const open=panel.hidden;closeMenus();panel.hidden=!open;button.setAttribute('aria-expanded',String(open))}});document.querySelectorAll<HTMLElement>('[data-menu-panel]').forEach(panel=>panel.hidden=true);document.addEventListener('click',closeMenus);
function show(tab:string){document.querySelectorAll('main>section').forEach(s=>(s as HTMLElement).hidden=s.id!==tab);if(tab==='history')void loadHistory()}
document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{if(!$('beforeAfter').hidden){beforeAfter.discard();void chrome.storage.session.remove('sidePanelMode')}show(b.dataset.tab!)});
async function blobFromUrl(url:string){const r=await fetch(url,{credentials:'include'});if(!r.ok)throw new Error('Изображение ChatGPT недоступно; загрузите его вручную');return r.blob()}
function preview(blob?:Blob){image=blob;const img=$<HTMLImageElement>('preview');if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=undefined;if(blob){previewUrl=URL.createObjectURL(blob);img.src=previewUrl;img.hidden=false}else{img.hidden=true;img.removeAttribute('src')}renderTelegramPreview(editor.document())}
beforeAfter=new BeforeAfterEditor({onCancel:()=>{show('publisher');void chrome.storage.session.remove('sidePanelMode')},onSave:async(blob,filename)=>{await downloadComposedImage(blob,filename);preview(blob);editor.set(plainTextToDocument(''));postId=undefined;key=crypto.randomUUID();last={};$('results').replaceChildren();show('publisher');void chrome.storage.session.remove('sidePanelMode')}});
function openBeforeAfter(){show('beforeAfter');beforeAfter.open()}
let draftVersion=0;
async function renderDraft(draft:PublisherDraft){const version=++draftVersion;editor.set(draft.postDocument,draft.publicationText??'');renderTelegramPreview(editor.document());const box=$('detected');box.replaceChildren();if(!draft.image){preview();return}const img=document.createElement('img');img.src=draft.image.url;img.className='candidate selected';img.title='Выбранное изображение';box.append(img);try{const selected=await blobFromUrl(draft.image.url);if(version===draftVersion)preview(selected)}catch(e){if(version===draftVersion){preview();box.append(document.createTextNode(`Не удалось прикрепить изображение: ${e instanceof Error?e.message:String(e)}`))}}}
async function draft(){const {draft}=await chrome.storage.session.get('draft');if(draft)renderDraft(draft)}
chrome.runtime.onMessage.addListener((message:unknown)=>{if(typeof message!=='object'||message===null)return;const type=(message as {type?:unknown}).type;if(type==='DRAFT_UPDATED'){show('publisher');void renderDraft((message as {draft:PublisherDraft}).draft)}if(type==='OPEN_BEFORE_AFTER_EDITOR')openBeforeAfter()});
$<HTMLInputElement>('upload').onchange=e=>preview((e.target as HTMLInputElement).files?.[0]);$('removeImage').onclick=()=>preview();
function renderResults(results:Partial<Record<Platform,PublicationResult>>){last={...last,...results};$('results').innerHTML=(['vk','telegram'] as Platform[]).filter(p=>last[p]).map(p=>`<div class="result ${last[p]!.status==='published'?'ok':'fail'}">${p.toUpperCase()}: ${last[p]!.status==='published'?(last[p]!.image_status==='manual_required'?'✓ Опубликовано без изображения — добавьте фото в VK вручную':'✓ Опубликовано'):'✗ '+(last[p]!.error??'Ошибка')}</div>`).join('')}
$('publish').onclick=async()=>{const targets=(['vk','telegram'] as Platform[]).filter(p=>( $(p) as HTMLInputElement).checked&&last[p]?.status!=='published');if(!targets.length)return alert('Выберите площадку или нет неуспешных площадок');const postDocument=editor.document(),text=editor.text().trim(),firstLine=text.split('\n').find(Boolean)?.replace(/^#+\s*/,'').slice(0,120)??'';const metadata={title:firstLine,topic:firstLine,summary:text.replace(/\s+/g,' ').slice(0,240),content_type:'freeform'};const b=$<HTMLButtonElement>('publish');b.disabled=true;b.textContent='Публикуем…';try{const r=await publish({text,postDocument,targets,metadata,postId,image,idempotencyKey:key});postId=r.post_id;renderResults(r.publications)}catch(e){$('results').textContent=e instanceof Error?e.message:String(e)}finally{b.disabled=false;b.textContent='Опубликовать'}};
function statuses(p:PostSummary){return (['vk','telegram'] as Platform[]).map(x=>`${x.toUpperCase()} ${p.publications[x]?.status==='published'?'✓':p.publications[x]?'✗':'—'}`).join(' · ')}
const historyImageUrls=new Set<string>(),detailImageUrls=new Set<string>();
function revokeUrls(urls:Set<string>){urls.forEach(url=>URL.revokeObjectURL(url));urls.clear()}
async function loadProtectedImage(element:HTMLImageElement,url:string,urls:Set<string>){try{const objectUrl=URL.createObjectURL(await protectedImage(url));urls.add(objectUrl);element.src=objectUrl}catch{element.remove()}}
async function loadHistory(){try{revokeUrls(historyImageUrls);const r=await posts($<HTMLInputElement>('search').value);$('cards').innerHTML=r.items.map(p=>`<div class="card" data-id="${p.id}">${p.image_url?'<img>':''}<b>${p.title||p.topic||'Публикация'}</b><div>${new Date(p.published_at||p.created_at).toLocaleDateString('ru-RU')}</div><p>${p.summary||p.text.slice(0,130)}</p><small>${statuses(p)}</small><div style="clear:both"></div></div>`).join('')||'<p>Публикаций нет.</p>';const byId=new Map(r.items.map(item=>[item.id,item]));document.querySelectorAll<HTMLElement>('.card').forEach(card=>{const item=byId.get(Number(card.dataset.id));const imageElement=card.querySelector<HTMLImageElement>('img');if(item?.image_url&&imageElement)void loadProtectedImage(imageElement,item.image_url,historyImageUrls);card.onclick=()=>void detail(Number(card.dataset.id))})}catch(e){$('cards').textContent=String(e)}}
async function detail(id:number){revokeUrls(detailImageUrls);const p=await post(id);$('detail').innerHTML=`<h2>${p.title||p.topic||'Публикация'}</h2>${p.image_url?'<img>':''}<p>${p.text.replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]!))}</p><p>${statuses(p)}</p>`;const imageElement=$('detail').querySelector<HTMLImageElement>('img');if(p.image_url&&imageElement)void loadProtectedImage(imageElement,p.image_url,detailImageUrls)}
$('searchButton').onclick=()=>void loadHistory();
let pairingTimer:number|undefined,pairingExpires=0;
function stopPairingPolling(){if(pairingTimer!==undefined)window.clearInterval(pairingTimer);pairingTimer=undefined}
function telegramError(error:unknown){$('telegramSettingsError').textContent=error instanceof ApiError?error.message:'Сервис временно недоступен. Повторите позже.'}
function showTelegramConnection(connection:TelegramConnection){stopPairingPolling();$('telegramDisconnected').hidden=connection.connected;$('telegramPairing').hidden=true;$('telegramConnected').hidden=!connection.connected;$('telegramChatTitle').textContent=connection.chatTitle??'';$('telegramSettingsError').textContent=''}
async function refreshTelegram(){try{showTelegramConnection(await telegramConnection())}catch(error){telegramError(error)}}
async function beginPairing(){stopPairingPolling();$('telegramSettingsError').textContent='';try{const pairing=await createTelegramPairing();$('telegramDisconnected').hidden=true;$('telegramConnected').hidden=true;$('telegramPairing').hidden=false;$('telegramCommand').textContent=pairing.command;pairingExpires=Date.parse(pairing.expiresAt);pairingTimer=window.setInterval(async()=>{if(Date.now()>=pairingExpires){stopPairingPolling();$('telegramWaiting').textContent='Код истёк. Создайте новый код.';return}try{const connection=await telegramConnection();if(connection.connected)showTelegramConnection(connection)}catch(error){telegramError(error)}},2500)}catch(error){telegramError(error)}}
$('telegramConnect').onclick=()=>void beginPairing();$('telegramChange').onclick=()=>void beginPairing();$('telegramCopy').onclick=async()=>{await navigator.clipboard.writeText($('telegramCommand').textContent??'');$('telegramWaiting').textContent='Команда скопирована. Ожидаем подключения…'};$('telegramCancel').onclick=()=>{stopPairingPolling();void refreshTelegram()};$('telegramDisconnect').onclick=async()=>{if(confirm('Отключить Telegram-группу?'))try{showTelegramConnection(await disconnectTelegram())}catch(error){telegramError(error)}};
chrome.storage.session.get('sidePanelMode').then(({sidePanelMode})=>{if(sidePanelMode==='before_after')openBeforeAfter();else void draft()});void refreshTelegram();
window.addEventListener('unload',()=>{revokeUrls(historyImageUrls);revokeUrls(detailImageUrls);stopPairingPolling();beforeAfter.discard();if(previewUrl)URL.revokeObjectURL(previewUrl)});
