import {deserializePostDocument,documentText,safeLink,type InlineMark,type PostBlock,type PostDocument,type TextRun} from '../../../shared/post-document';
type BlockType=PostBlock['type'];
const inlineTypes=['bold','italic','underline','strikethrough','spoiler'] as const;
const textOf=(runs:TextRun[])=>runs.map(run=>run.text).join('');
function runsWithMark(runs:TextRun[],start:number,end:number,mark:InlineMark|null,removeType?:InlineMark['type']){const out:TextRun[]=[];let offset=0;for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)out.push({text:run.text.slice(0,from),marks:run.marks});if(to>from){const marks=(run.marks??[]).filter(m=>m.type!==(removeType??mark?.type));if(mark)marks.push(mark);out.push({text:run.text.slice(from,to),...(marks.length?{marks}:{})})}if(to<run.text.length)out.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length}return out.filter(run=>run.text.length)}
function clearRuns(runs:TextRun[],start:number,end:number){let offset=0;const out:TextRun[]=[];for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)out.push({text:run.text.slice(0,from),marks:run.marks});if(to>from)out.push({text:run.text.slice(from,to)});if(to<run.text.length)out.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length}return out}
function nodeOffset(root:Node,node:Node,offset:number){const range=document.createRange();range.setStart(root,0);range.setEnd(node,offset);return range.toString().length}
type SavedSelection={startIndex:number;start:number;endIndex:number;end:number};
export class PostEditor{
 private value:PostDocument;private undo:PostDocument[]=[];private redo:PostDocument[]=[];private saved:SavedSelection|null=null;private editingIndex:number|null=null;
 constructor(private root:HTMLElement,initial:unknown,fallback:string,private onChange:(value:PostDocument)=>void){this.value=deserializePostDocument(initial,fallback);root.contentEditable='true';this.render();root.addEventListener('beforeinput',()=>{this.capture();this.editingIndex=this.saved?.startIndex??null});root.addEventListener('input',()=>this.input());root.addEventListener('mouseup',()=>this.capture());root.addEventListener('keyup',()=>this.capture())}
 document(){return structuredClone(this.value)} text(){return documentText(this.value)}
 set(value:unknown,fallback=''){this.value=deserializePostDocument(value,fallback);this.undo=[];this.redo=[];this.render()}
 private checkpoint(){this.undo.push(structuredClone(this.value));if(this.undo.length>100)this.undo.shift();this.redo=[]}
 private changed(){this.render();this.onChange(this.document())}
 private input(){const index=this.editingIndex;if(index===null)return;const element=this.root.querySelector<HTMLElement>(`[data-block="${index}"]`),block=this.value.blocks[index];if(!element||!block)return;this.checkpoint();const editable=element.querySelector<HTMLElement>('.editor-details-body')??element,content=[{text:editable.innerText.replace(/\n$/,'')}];if('items'in block)block.items=[content];else block.content=content;this.onChange(this.document())}
 private point(node:Node|null,offset:number){const element=(node instanceof Element?node:node?.parentElement)?.closest<HTMLElement>('[data-block]');if(!element||!this.root.contains(element))return null;return {index:Number(element.dataset.block),offset:nodeOffset(element,node!,offset)}}
 private capture(){const selection=getSelection();if(!selection)return;const a=this.point(selection.anchorNode,selection.anchorOffset),f=this.point(selection.focusNode,selection.focusOffset);if(!a||!f)return;const forward=a.index<f.index||(a.index===f.index&&a.offset<=f.offset);const start=forward?a:f,end=forward?f:a;this.saved={startIndex:start.index,start:start.offset,endIndex:end.index,end:end.offset}}
 private selected(){this.capture();return this.saved}
 private rangeFor(block:PostBlock,index:number,s:SavedSelection){const runs='items'in block?block.items[0]??[]:block.content,length=textOf(runs).length;return {runs,start:index===s.startIndex?s.start:0,end:index===s.endIndex?s.end:length}}
 applyMark(type:typeof inlineTypes[number]){const s=this.selected();if(!s)return false;const selected=this.value.blocks.slice(s.startIndex,s.endIndex+1);if(!selected.length)return false;const active=selected.every((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s);return end>start&&runs.filter((run,index)=>{const before=runs.slice(0,index).reduce((n,r)=>n+r.text.length,0);return before<end&&before+run.text.length>start}).every(run=>run.marks?.some(mark=>mark.type===type))});this.checkpoint();selected.forEach((block,i)=>{const index=s.startIndex+i,{runs,start,end}=this.rangeFor(block,index,s),next=runsWithMark(runs,start,end,active?null:{type},active?type:undefined);if('items'in block)block.items[0]=next;else block.content=next});this.changed();return !active}
 link(){const s=this.selected();if(!s)return;const href=prompt('HTTPS-ссылка');if(href===null)return;const valid=safeLink(href);if(!valid){alert('Разрешены только ссылки http:// и https://');return}this.checkpoint();this.value.blocks.slice(s.startIndex,s.endIndex+1).forEach((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s),next=runsWithMark(runs,start,end,{type:'link',href:valid});if('items'in block)block.items[0]=next;else block.content=next});this.changed()}
 clear(){const s=this.selected();if(!s)return;this.checkpoint();this.value.blocks.slice(s.startIndex,s.endIndex+1).forEach((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s),next=clearRuns(runs,start,end);if('items'in block)block.items[0]=next;else block.content=next});this.changed()}
 block(type:BlockType){const s=this.selected()??{startIndex:0,start:0,endIndex:0,end:0};this.checkpoint();for(let index=s.startIndex;index<=s.endIndex;index++){const old=this.value.blocks[index],content='items'in old?old.items.flatMap((item,i)=>i?[{text:'\n'},...item]:item):old.content;if(type==='bullet_list'||type==='ordered_list')this.value.blocks[index]={type,items:[content]};else if(type==='details'){const title=prompt('Заголовок выпадающего блока','Подробнее')?.trim()||'Подробнее';this.value.blocks[index]={type,title:[{text:title}],content,emoji:'✨'}}else this.value.blocks[index]={type,content}}this.changed()}
 emoji(){const emoji=prompt('Emoji','✨');if(!emoji)return;const s=this.selected()??{startIndex:0,start:0,endIndex:0,end:0},block=this.value.blocks[s.endIndex],runs='items'in block?block.items[0]:block.content,raw=textOf(runs);this.checkpoint();const replacement=[{text:raw.slice(0,s.end)+emoji+raw.slice(s.end)}];if('items'in block)block.items[0]=replacement;else block.content=replacement;this.changed()}
 history(direction:'undo'|'redo'){const from=direction==='undo'?this.undo:this.redo,to=direction==='undo'?this.redo:this.undo,next=from.pop();if(!next)return;to.push(structuredClone(this.value));this.value=next;this.changed()}
 private renderRuns(container:HTMLElement,runs:TextRun[]){for(const run of runs){let node:Node=document.createTextNode(run.text);for(const mark of run.marks??[]){const el=document.createElement(mark.type==='link'?'a':mark.type==='bold'?'strong':mark.type==='italic'?'em':mark.type==='underline'?'u':mark.type==='strikethrough'?'s':'span');if(mark.type==='spoiler')el.className='spoiler';if(mark.type==='link'){const href=safeLink(mark.href);if(href)(el as HTMLAnchorElement).href=href}el.append(node);node=el}container.append(node)}}
 private render(){this.root.replaceChildren();this.value.blocks.forEach((block,index)=>{const el=document.createElement('div');el.dataset.block=String(index);el.className=`editor-block ${block.type}`;if('items'in block){el.dataset.prefix=block.type==='bullet_list'?'•':'1.';this.renderRuns(el,block.items[0]??[{text:''}])}else if(block.type==='details'&&block.title?.length){const title=document.createElement('span');title.className='details-title';title.contentEditable='false';this.renderRuns(title,block.title);el.append(title);const body=document.createElement('span');body.className='editor-details-body';this.renderRuns(body,block.content);el.append(body)}else this.renderRuns(el,block.content);if(!el.textContent)el.append(document.createElement('br'));this.root.append(el)})}
}
