import {deserializePostDocument, documentText, safeLink, type InlineMark, type PostBlock, type PostDocument, type TextRun} from '../../../shared/post-document';

type BlockType=PostBlock['type'];
const inlineTypes=['bold','italic','underline','strikethrough','spoiler'] as const;
const textOf=(runs:TextRun[])=>runs.map(run=>run.text).join('');
function runsWithMark(runs:TextRun[],start:number,end:number,mark:InlineMark|null):TextRun[]{
  const output:TextRun[]=[];let offset=0;
  for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)output.push({text:run.text.slice(0,from),marks:run.marks});if(to>from){const marks=(run.marks??[]).filter(m=>mark?.type==='link'?m.type!=='link':m.type!==mark?.type);if(mark)marks.push(mark);output.push({text:run.text.slice(from,to),...(marks.length?{marks}:{})});}if(to<run.text.length)output.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length;}
  return output.filter(run=>run.text.length);
}
function clearRuns(runs:TextRun[],start:number,end:number){let offset=0;const output:TextRun[]=[];for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)output.push({text:run.text.slice(0,from),marks:run.marks});if(to>from)output.push({text:run.text.slice(from,to)});if(to<run.text.length)output.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length;}return output;}
function nodeOffset(root:Node,node:Node,offset:number){const range=document.createRange();range.setStart(root,0);range.setEnd(node,offset);return range.toString().length;}
export class PostEditor{
  private value:PostDocument;private undo:PostDocument[]=[];private redo:PostDocument[]=[];private saved:{index:number;start:number;end:number}|null=null;
  constructor(private root:HTMLElement,initial:unknown,fallback:string,private onChange:(value:PostDocument)=>void){this.value=deserializePostDocument(initial,fallback);this.render();root.addEventListener('input',e=>this.input(e));root.addEventListener('mouseup',()=>this.capture());root.addEventListener('keyup',()=>this.capture());}
  document(){return structuredClone(this.value)} text(){return documentText(this.value)}
  set(value:unknown,fallback=''){this.value=deserializePostDocument(value,fallback);this.undo=[];this.redo=[];this.render();}
  private checkpoint(){this.undo.push(structuredClone(this.value));if(this.undo.length>100)this.undo.shift();this.redo=[];}
  private changed(){this.render();this.onChange(this.document());}
  private input(event:Event){const element=(event.target as HTMLElement).closest<HTMLElement>('[data-block]');if(!element)return;const index=Number(element.dataset.block),block=this.value.blocks[index];this.checkpoint();const content=[{text:element.innerText.replace(/\n$/,'')}];if('items'in block)block.items=[content];else block.content=content;this.onChange(this.document());}
  private capture(){const selection=getSelection(),anchor=selection?.anchorNode;if(!selection||!anchor)return;const element=(anchor instanceof Element?anchor:anchor.parentElement)?.closest<HTMLElement>('[data-block]');if(!element||!this.root.contains(element))return;this.saved={index:Number(element.dataset.block),start:nodeOffset(element,selection.anchorNode!,selection.anchorOffset),end:nodeOffset(element,selection.focusNode!,selection.focusOffset)};if(this.saved.start>this.saved.end)[this.saved.start,this.saved.end]=[this.saved.end,this.saved.start];}
  private selected(){this.capture();return this.saved;}
  applyMark(type:typeof inlineTypes[number]){const s=this.selected();if(!s||s.start===s.end)return;const block=this.value.blocks[s.index],runs='items'in block?block.items[0]:block.content;const active=runs.some(run=>run.marks?.some(mark=>mark.type===type));this.checkpoint();const next=runsWithMark(runs,s.start,s.end,active?null:{type});if('items'in block)block.items[0]=next;else block.content=next;this.changed();}
  link(){const s=this.selected();if(!s||s.start===s.end)return;const href=prompt('HTTPS-ссылка');if(href===null)return;const valid=safeLink(href);if(!valid){alert('Разрешены только ссылки http:// и https://');return;}const block=this.value.blocks[s.index],runs='items'in block?block.items[0]:block.content;this.checkpoint();const next=runsWithMark(runs,s.start,s.end,{type:'link',href:valid});if('items'in block)block.items[0]=next;else block.content=next;this.changed();}
  clear(){const s=this.selected();if(!s||s.start===s.end)return;const block=this.value.blocks[s.index],runs='items'in block?block.items[0]:block.content;this.checkpoint();const next=clearRuns(runs,s.start,s.end);if('items'in block)block.items[0]=next;else block.content=next;this.changed();}
  block(type:BlockType){const s=this.selected()??{index:0,start:0,end:0},old=this.value.blocks[s.index];this.checkpoint();const content='items'in old?old.items.flatMap((item,i)=>i?[{text:'\n'},...item]:item):old.content;if(type==='bullet_list'||type==='ordered_list')this.value.blocks[s.index]={type,items:[content]};else this.value.blocks[s.index]={type,content,...(type==='details'?{emoji:'✨'}:{})};this.changed();}
  emoji(){const emoji=prompt('Emoji','✨');if(!emoji)return;const s=this.selected()??{index:0,start:0,end:0},block=this.value.blocks[s.index],runs='items'in block?block.items[0]:block.content;this.checkpoint();const pos=s.end,next=runsWithMark(runs,pos,pos,null);const raw=textOf(runs);const replacement=[{text:raw.slice(0,pos)+emoji+raw.slice(pos)}];if('items'in block)block.items[0]=replacement;else block.content=replacement;this.changed();}
  history(direction:'undo'|'redo'){const from=direction==='undo'?this.undo:this.redo,to=direction==='undo'?this.redo:this.undo,next=from.pop();if(!next)return;to.push(structuredClone(this.value));this.value=next;this.changed();}
  private renderRuns(container:HTMLElement,runs:TextRun[]){for(const run of runs){let node:Node=document.createTextNode(run.text);for(const mark of run.marks??[]){const el=document.createElement(mark.type==='link'?'a':mark.type==='bold'?'strong':mark.type==='italic'?'em':mark.type==='underline'?'u':mark.type==='strikethrough'?'s':'span');if(mark.type==='spoiler')el.className='spoiler';if(mark.type==='link'){const href=safeLink(mark.href);if(href)(el as HTMLAnchorElement).href=href;}el.append(node);node=el;}container.append(node);}}
  private render(){this.root.replaceChildren();this.value.blocks.forEach((block,index)=>{const el=document.createElement('div');el.contentEditable='true';el.dataset.block=String(index);el.className=`editor-block ${block.type}`;if('items'in block){el.dataset.prefix=block.type==='bullet_list'?'•':'1.';this.renderRuns(el,block.items[0]??[{text:''}]);}else this.renderRuns(el,block.content);if(!el.textContent)el.append(document.createElement('br'));this.root.append(el);});}
}
