import {deserializePostDocument,documentText,safeLink,type InlineMark,type PostBlock,type PostDocument,type TextRun} from '../../../shared/post-document';
type BlockType=PostBlock['type'];
const inlineTypes=['bold','italic','underline','strikethrough','spoiler'] as const;
const textOf=(runs:TextRun[])=>runs.map(run=>run.text).join('');
function runsWithMark(runs:TextRun[],start:number,end:number,mark:InlineMark|null,removeType?:InlineMark['type']){const out:TextRun[]=[];let offset=0;for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)out.push({text:run.text.slice(0,from),marks:run.marks});if(to>from){const marks=(run.marks??[]).filter(m=>m.type!==(removeType??mark?.type));if(mark)marks.push(mark);out.push({text:run.text.slice(from,to),...(marks.length?{marks}:{})})}if(to<run.text.length)out.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length}return out.filter(run=>run.text.length)}
function clearRuns(runs:TextRun[],start:number,end:number){let offset=0;const out:TextRun[]=[];for(const run of runs){const from=Math.max(0,start-offset),to=Math.min(run.text.length,end-offset);if(from>0)out.push({text:run.text.slice(0,from),marks:run.marks});if(to>from)out.push({text:run.text.slice(from,to)});if(to<run.text.length)out.push({text:run.text.slice(Math.max(to,0)),marks:run.marks});offset+=run.text.length}return out}
function nodeOffset(root:Node,node:Node,offset:number){const range=document.createRange();range.setStart(root,0);range.setEnd(node,offset);return range.toString().length}
function splitRuns(runs:TextRun[],position:number):[TextRun[],TextRun[]]{const before:TextRun[]=[],after:TextRun[]=[];let offset=0;for(const run of runs){const split=Math.max(0,Math.min(run.text.length,position-offset));if(split)before.push({text:run.text.slice(0,split),marks:run.marks});if(split<run.text.length)after.push({text:run.text.slice(split),marks:run.marks});offset+=run.text.length}return [before.length?before:[{text:''}],after.length?after:[{text:''}]]}
type SavedSelection={startIndex:number;start:number;endIndex:number;end:number};
export class PostEditor{
 private value:PostDocument;private undo:PostDocument[]=[];private redo:PostDocument[]=[];private saved:SavedSelection|null=null;private editingIndex:number|null=null;private editingTitle=false;
 constructor(private root:HTMLElement,initial:unknown,fallback:string,private onChange:(value:PostDocument)=>void){this.value=deserializePostDocument(initial,fallback);root.contentEditable='true';this.render();root.addEventListener('beforeinput',event=>this.beforeInput(event as InputEvent));root.addEventListener('input',()=>this.input());root.addEventListener('mouseup',()=>this.capture());root.addEventListener('keyup',()=>this.capture())}
 document(){return structuredClone(this.value)} text(){return documentText(this.value)}
 set(value:unknown,fallback=''){this.value=deserializePostDocument(value,fallback);this.undo=[];this.redo=[];this.render()}
 private checkpoint(){this.undo.push(structuredClone(this.value));if(this.undo.length>100)this.undo.shift();this.redo=[]}
 private changed(){this.render();this.onChange(this.document())}
 private beforeInput(event:InputEvent){this.capture();this.editingIndex=this.saved?.startIndex??null;const selection=getSelection(),anchor=selection?.anchorNode,element=anchor instanceof Element?anchor:anchor?.parentElement;this.editingTitle=!!element?.closest('.details-title');const row=element?.closest<HTMLElement>('[data-list-item]'),blockElement=row?.closest<HTMLElement>('[data-block]');if(!row||!blockElement)return;const blockIndex=Number(blockElement.dataset.block),itemIndex=Number(row.dataset.listItem),block=this.value.blocks[blockIndex];if(!block||!('items'in block))return;if(event.inputType==='insertParagraph'){event.preventDefault();const position=nodeOffset(row,selection!.anchorNode!,selection!.anchorOffset),[before,after]=splitRuns(block.items[itemIndex],position);this.checkpoint();block.items.splice(itemIndex,1,before,after);this.changed();this.focusListItem(blockIndex,itemIndex+1,0)}else if(event.inputType==='deleteContentBackward'&&textOf(block.items[itemIndex])===''&&itemIndex>0){event.preventDefault();this.checkpoint();block.items.splice(itemIndex,1);const position=textOf(block.items[itemIndex-1]).length;this.changed();this.focusListItem(blockIndex,itemIndex-1,position)}}
 private focusListItem(blockIndex:number,itemIndex:number,position:number){const row=this.root.querySelector<HTMLElement>(`[data-block="${blockIndex}"] [data-list-item="${itemIndex}"]`);if(!row)return;const node=row.firstChild??row,range=document.createRange(),selection=getSelection();range.setStart(node,Math.min(position,node.textContent?.length??0));range.collapse(true);selection?.removeAllRanges();selection?.addRange(range);this.capture()}
 private input(){const index=this.editingIndex;if(index===null)return;const element=this.root.querySelector<HTMLElement>(`[data-block="${index}"]`),block=this.value.blocks[index];if(!element||!block)return;this.checkpoint();if(block.type==='details'&&this.editingTitle){const title=element.querySelector<HTMLElement>('.details-title')?.innerText.trim()??'';block.title=title?[{text:title}]:[]}else if('items'in block){block.items=[...element.querySelectorAll<HTMLElement>('[data-list-item]')].map(item=>[{text:item.innerText.replace(/\n$/,'')}])}else{const editable=element.querySelector<HTMLElement>('.editor-details-body')??element;block.content=[{text:editable.innerText.replace(/\n$/,'')}]}this.onChange(this.document())}
 private point(node:Node|null,offset:number){const element=(node instanceof Element?node:node?.parentElement)?.closest<HTMLElement>('[data-block]');if(!element||!this.root.contains(element))return null;return {index:Number(element.dataset.block),offset:nodeOffset(element,node!,offset)}}
 private capture(){const selection=getSelection();if(!selection)return;const a=this.point(selection.anchorNode,selection.anchorOffset),f=this.point(selection.focusNode,selection.focusOffset);if(!a||!f)return;const forward=a.index<f.index||(a.index===f.index&&a.offset<=f.offset);const start=forward?a:f,end=forward?f:a;this.saved={startIndex:start.index,start:start.offset,endIndex:end.index,end:end.offset}}
 private selected(){this.capture();return this.saved}
 private rangeFor(block:PostBlock,index:number,s:SavedSelection){const runs='items'in block?block.items[0]??[]:block.content,length=textOf(runs).length;return {runs,start:index===s.startIndex?s.start:0,end:index===s.endIndex?s.end:length}}
 applyMark(type:typeof inlineTypes[number]){const s=this.selected();if(!s)return false;const selected=this.value.blocks.slice(s.startIndex,s.endIndex+1);if(!selected.length)return false;const active=selected.every((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s);return end>start&&runs.filter((run,index)=>{const before=runs.slice(0,index).reduce((n,r)=>n+r.text.length,0);return before<end&&before+run.text.length>start}).every(run=>run.marks?.some(mark=>mark.type===type))});this.checkpoint();selected.forEach((block,i)=>{const index=s.startIndex+i,{runs,start,end}=this.rangeFor(block,index,s),next=runsWithMark(runs,start,end,active?null:{type},active?type:undefined);if('items'in block)block.items[0]=next;else block.content=next});this.changed();return !active}
 link(){const s=this.selected();if(!s)return;const href=prompt('HTTPS-ссылка');if(href===null)return;const valid=safeLink(href);if(!valid){alert('Разрешены только ссылки http:// и https://');return}this.checkpoint();this.value.blocks.slice(s.startIndex,s.endIndex+1).forEach((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s),next=runsWithMark(runs,start,end,{type:'link',href:valid});if('items'in block)block.items[0]=next;else block.content=next});this.changed()}
 clear(){const s=this.selected();if(!s)return;this.checkpoint();this.value.blocks.slice(s.startIndex,s.endIndex+1).forEach((block,i)=>{const {runs,start,end}=this.rangeFor(block,s.startIndex+i,s),next=clearRuns(runs,start,end);if('items'in block)block.items[0]=next;else block.content=next});this.changed()}
 block(type:BlockType){const s=this.selected()??{startIndex:0,start:0,endIndex:0,end:0},selected=this.value.blocks.slice(s.startIndex,s.endIndex+1);if(selected.length===1&&selected[0].type===type){this.checkpoint();const block=selected[0];if('items'in block)this.value.blocks.splice(s.startIndex,1,...block.items.map(content=>({type:'paragraph' as const,content})));else this.value.blocks.splice(s.startIndex,1,{type:'paragraph',content:block.content});this.changed();this.focusBlockEnd(s.startIndex);return false}const contents=selected.flatMap(block=>'items'in block?block.items:[block.content]);this.checkpoint();if(type==='bullet_list'||type==='ordered_list')this.value.blocks.splice(s.startIndex,selected.length,{type,items:contents});else if(type==='quote'||type==='details'){const content=contents.flatMap((runs,index)=>index?[{text:'\n\n'},...runs]:runs);this.value.blocks.splice(s.startIndex,selected.length,type==='details'?{type,title:[],content,emoji:'✨'}:{type,content})}else for(let index=s.startIndex;index<=s.endIndex;index++){const old=this.value.blocks[index],content='items'in old?old.items.flatMap((item,i)=>i?[{text:'\n'},...item]:item):old.content;this.value.blocks[index]={type,content}}this.changed();this.focusBlockEnd(s.startIndex);return true}
 private focusBlockEnd(index:number){const block=this.root.querySelector<HTMLElement>(`[data-block="${index}"]`);if(!block)return;const target=block.querySelector<HTMLElement>('[data-list-item]:last-child')??block,node=target.lastChild??target,range=document.createRange(),selection=getSelection();range.selectNodeContents(node);range.collapse(false);selection?.removeAllRanges();selection?.addRange(range);this.capture()}
 button(){const text=prompt('Текст кнопки')?.trim();if(!text)return;const href=prompt('URL кнопки')?.trim(),url=href&&safeLink(href);if(!url){alert('Разрешены только ссылки http:// и https://');return}this.checkpoint();this.value.buttons=[...(this.value.buttons??[]),{text,url}];this.changed()}
 emoji(){const emoji=prompt('Emoji','✨');if(!emoji)return;const s=this.selected()??{startIndex:0,start:0,endIndex:0,end:0},block=this.value.blocks[s.endIndex],runs='items'in block?block.items[0]:block.content,raw=textOf(runs);this.checkpoint();const replacement=[{text:raw.slice(0,s.end)+emoji+raw.slice(s.end)}];if('items'in block)block.items[0]=replacement;else block.content=replacement;this.changed()}
 history(direction:'undo'|'redo'){const from=direction==='undo'?this.undo:this.redo,to=direction==='undo'?this.redo:this.undo,next=from.pop();if(!next)return;to.push(structuredClone(this.value));this.value=next;this.changed()}
 private renderRuns(container:HTMLElement,runs:TextRun[]){for(const run of runs){let node:Node=document.createTextNode(run.text);for(const mark of run.marks??[]){const el=document.createElement(mark.type==='link'?'a':mark.type==='bold'?'strong':mark.type==='italic'?'em':mark.type==='underline'?'u':mark.type==='strikethrough'?'s':'span');if(mark.type==='spoiler')el.className='spoiler';if(mark.type==='link'){const href=safeLink(mark.href);if(href)(el as HTMLAnchorElement).href=href}el.append(node);node=el}container.append(node)}}
 private render(){this.root.replaceChildren();this.value.blocks.forEach((block,index)=>{const el=document.createElement('div');el.dataset.block=String(index);el.className=`editor-block ${block.type}`;if('items'in block){block.items.forEach((item,itemIndex)=>{const row=document.createElement('div');row.dataset.listItem=String(itemIndex);row.dataset.prefix=block.type==='bullet_list'?'•':`${itemIndex+1}.`;this.renderRuns(row,item);if(!row.textContent)row.append(document.createElement('br'));el.append(row)})}else if(block.type==='details'){const header=document.createElement('div');header.className='details-header';const toggle=document.createElement('button');toggle.type='button';toggle.className='details-toggle';toggle.contentEditable='false';toggle.setAttribute('aria-label','Раскрыть details');toggle.setAttribute('aria-expanded','false');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','m6 9 6 6 6-6');svg.append(path);toggle.append(svg);const title=document.createElement('span');title.className='details-title';title.dataset.placeholder='Вставьте заголовок';this.renderRuns(title,block.title??[]);if(!title.textContent)title.append(document.createElement('br'));header.append(toggle,title);el.append(header);const body=document.createElement('span');body.className='editor-details-body';body.hidden=true;this.renderRuns(body,block.content);toggle.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const expanded=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!expanded));toggle.setAttribute('aria-label',expanded?'Раскрыть details':'Свернуть details');el.classList.toggle('expanded',!expanded);body.hidden=expanded});el.append(body)}else this.renderRuns(el,block.content);if(!el.textContent)el.append(document.createElement('br'));this.root.append(el)});if(this.value.buttons?.length){const buttons=document.createElement('div');buttons.className='editor-buttons';this.value.buttons.forEach(button=>{const chip=document.createElement('span');chip.textContent=button.text;buttons.append(chip)});this.root.append(buttons)}}
}
