(()=>{
const photos={before:null,after:null};let layout='horizontal',pending='before',editing=null,mode='photo',editSnapshot=null,cropHeight=null,selectedWatermark=null,watermarkState={x:0,y:0,scale:1,rotation:0};
const $=id=>document.getElementById(id),slots=$('slots'),file=$('file'),editor=$('editor'),stage=$('stage'),editImage=$('editImage'),wmImage=$('watermarkImage'),rotation=$('rotation'),cropHandle=$('cropHandle'),wmFile=$('watermarkFile'),wmCarousel=$('watermarkCarousel');
const webApp=window.Telegram?.WebApp;const authHeaders=()=>webApp?.initData?{Authorization:`tma ${webApp.initData}`}:{ };
function transformFor(p){return `translate(calc(-50% + ${p.x}px),calc(-50% + ${p.y}px)) scale(${p.scale}) rotate(${p.rotation}deg)`}
function render(){slots.dataset.layout=layout;document.querySelectorAll('[data-layout]').forEach(b=>b.classList.toggle('selected',b.dataset.layout===layout));['before','after'].forEach(s=>{const el=document.querySelector(`[data-slot=${s}]`),img=el.querySelector('img'),p=photos[s];el.classList.toggle('loaded',!!p);if(p){img.src=p.url;img.style.width=`${p.img.naturalWidth}px`;img.style.height=`${p.img.naturalHeight}px`;img.style.transform=transformFor(p)}});$('finish').disabled=!(photos.before||photos.after)}
function setInitialCompositeSize(){slots.style.aspectRatio=layout==='horizontal'?'8/3':'4/6';slots.style.height='';cropHeight=null}
function setEditorGeometryFromRect(r){const controls=document.querySelector('.editor-controls').getBoundingClientRect().height,available=editor.clientHeight-58-controls,scale=Math.min(window.innerWidth/r.width,Math.max(1,available)/r.height);stage.style.width=`${r.width*scale}px`;stage.style.height=`${r.height*scale}px`;stage.dataset.geometryScale=String(scale)}
function setEditorGeometry(s){setEditorGeometryFromRect(document.querySelector(`[data-slot=${s}]`).getBoundingClientRect())}
document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>{layout=b.dataset.layout;slots.dataset.layout=layout;setInitialCompositeSize();requestAnimationFrame(()=>{refitForComposite();render()})});
document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const s=b.dataset.slot;if(photos[s])openEditor(s);else{pending=s;file.click()}});
file.onchange=()=>{const f=file.files?.[0];file.value='';if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type))return showError('Поддерживаются JPEG, PNG и WebP.');const url=URL.createObjectURL(f),img=new Image();img.onload=()=>{if(photos[pending])URL.revokeObjectURL(photos[pending].url);photos[pending]={file:f,url,img,x:0,y:0,scale:1,rotation:0,fitted:false};render();openEditor(pending)};img.src=url};
$('swap').onclick=()=>{[photos.before,photos.after]=[photos.after,photos.before];render()};
function transform(){const g=Number(stage.dataset.geometryScale||1);if(mode==='watermark'){const p=watermarkState;wmImage.style.transform=`translate(calc(-50% + ${p.x*g}px),calc(-50% + ${p.y*g}px)) scale(${p.scale*g}) rotate(${p.rotation}deg)`;return}if(!editing)return;const p=photos[editing];editImage.style.width=`${p.img.naturalWidth}px`;editImage.style.height=`${p.img.naturalHeight}px`;editImage.style.transform=`translate(calc(-50% + ${p.x*g}px),calc(-50% + ${p.y*g}px)) scale(${p.scale*g}) rotate(${p.rotation}deg)`}
function fit(p,r){p.scale=Math.max(r.width/p.img.naturalWidth,r.height/p.img.naturalHeight);p.x=p.y=0;p.fitted=true}
function refitForComposite(){['before','after'].forEach(s=>{const p=photos[s],slot=document.querySelector(`[data-slot=${s}]`);if(!p||!slot)return;const r=slot.getBoundingClientRect(),min=Math.max(r.width/p.img.naturalWidth,r.height/p.img.naturalHeight);if(p.scale<min)p.scale=min})}
function openEditor(s){mode='photo';editing=s;wmImage.hidden=true;editImage.hidden=false;const p=photos[s],slotRect=document.querySelector(`[data-slot=${s}]`).getBoundingClientRect();editSnapshot={...p};if(!p.fitted)fit(p,slotRect);editor.hidden=false;$('editorTitle').textContent=s==='before'?'До':'После';$('editorHint').textContent='Двигайте фото одним пальцем. Масштабируйте двумя.';editImage.src=p.url;requestAnimationFrame(()=>{setEditorGeometry(s);rotation.value=String(p.rotation);$('angle').textContent=`${p.rotation}°`;transform()})}
$('editorCancel').onclick=()=>{if(mode==='photo'&&editing&&editSnapshot)Object.assign(photos[editing],editSnapshot);if(mode==='watermark'&&editSnapshot)watermarkState={...editSnapshot};closeEditor();render()};
$('editorSave').onclick=()=>{closeEditor();requestAnimationFrame(()=>{refitForComposite();render()})};
function closeEditor(){editor.hidden=true;editing=null;editSnapshot=null;mode='photo'}
rotation.oninput=()=>{const p=mode==='watermark'?watermarkState:photos[editing];if(!p)return;p.rotation=Number(rotation.value);$('angle').textContent=`${rotation.value}°`;transform()};
$('gridToggle').onclick=()=>{const g=$('grid');g.hidden=!g.hidden;$('gridToggle').textContent=g.hidden?'Показать сетку':'Скрыть сетку'};
const pointers=new Map;let gesture=null;const point=e=>({x:e.clientX,y:e.clientY});function activeState(){return mode==='watermark'?watermarkState:photos[editing]}
function beginGesture(){const p=activeState();if(!p)return;const a=[...pointers.values()],g=Number(stage.dataset.geometryScale||1);if(a.length===1)gesture={type:'pan',start:a[0],x:p.x,y:p.y,g};else if(a.length>=2)gesture={type:'pinch',distance:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),scale:p.scale}}
stage.onpointerdown=e=>{stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,point(e));beginGesture()};stage.onpointermove=e=>{const p=activeState();if(!p||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,point(e));const a=[...pointers.values()];if(a.length===1){if(!gesture||gesture.type!=='pan')beginGesture();p.x=gesture.x+(a[0].x-gesture.start.x)/gesture.g;p.y=gesture.y+(a[0].y-gesture.start.y)/gesture.g}else if(a.length>=2){if(!gesture||gesture.type!=='pinch')beginGesture();const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);p.scale=Math.max(.05,Math.min(10,gesture.scale*d/Math.max(1,gesture.distance)))}transform()};function end(e){pointers.delete(e.pointerId);beginGesture()}stage.onpointerup=end;stage.onpointercancel=end;
let cropGesture=null;cropHandle.onpointerdown=e=>{e.preventDefault();e.stopPropagation();cropGesture={startY:e.clientY,startHeight:slots.getBoundingClientRect().height};cropHandle.setPointerCapture?.(e.pointerId)};cropHandle.onpointermove=e=>{if(!cropGesture)return;e.preventDefault();const next=Math.max(120,Math.min(Math.max(120,window.innerHeight-120),cropGesture.startHeight+e.clientY-cropGesture.startY));cropHeight=next;slots.style.height=`${next}px`;slots.style.aspectRatio='auto';requestAnimationFrame(()=>{refitForComposite();render()})};cropHandle.onpointerup=cropHandle.onpointercancel=e=>{cropGesture=null;cropHandle.releasePointerCapture?.(e.pointerId)};
function drawPhoto(ctx,p,r,k){if(!p)return;ctx.save();ctx.beginPath();ctx.rect(r.x*k,r.y*k,r.width*k,r.height*k);ctx.clip();ctx.translate((r.x+r.width/2+p.x)*k,(r.y+r.height/2+p.y)*k);ctx.rotate(p.rotation*Math.PI/180);ctx.scale(p.scale*k,p.scale*k);ctx.drawImage(p.img,-p.img.naturalWidth/2,-p.img.naturalHeight/2);ctx.restore()}
async function compositeBlob(){const sr=slots.getBoundingClientRect(),k=Math.min(3,Math.max(1,1080/sr.width)),c=document.createElement('canvas');c.width=Math.round(sr.width*k);c.height=Math.round(sr.height*k);const ctx=c.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,c.width,c.height);['before','after'].forEach(s=>{const r=document.querySelector(`[data-slot=${s}]`).getBoundingClientRect();drawPhoto(ctx,photos[s],{x:r.left-sr.left,y:r.top-sr.top,width:r.width,height:r.height},k)});return new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.94))}
async function processedWatermark(file){const img=await loadImage(URL.createObjectURL(file)),max=1200,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');ctx.filter='grayscale(1)';ctx.globalAlpha=.1;ctx.drawImage(img,0,0,c.width,c.height);return new Promise(resolve=>c.toBlob(b=>resolve(new File([b],file.name.replace(/\.[^.]+$/,'.png'),{type:'image/png'})),'image/png'))}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
async function fetchWmBlob(id){const r=await fetch(`/api/miniapp/watermarks/${encodeURIComponent(id)}`,{headers:authHeaders()});if(!r.ok)throw new Error('Не удалось загрузить водяной знак');return r.blob()}
async function loadWatermarks(){if(!webApp?.initData)return;try{const r=await fetch('/api/miniapp/watermarks',{headers:authHeaders()}),data=await r.json();if(!r.ok)throw new Error(data?.error?.message||'Не удалось загрузить водяные знаки');for(const wm of data.watermarks||[])await appendWatermark(wm)}catch(e){showError(e.message)}}
async function appendWatermark(wm){if(wmCarousel.querySelector(`[data-watermark="${CSS.escape(wm.id)}"]`))return;const b=document.createElement('button');b.type='button';b.className='watermark-item';b.dataset.watermark=wm.id;const blob=await fetchWmBlob(wm.id),url=URL.createObjectURL(blob);b.dataset.url=url;b.innerHTML=`<img alt=""><span hidden></span>`;b.querySelector('img').src=url;b.onclick=()=>selectWatermark(b);wmCarousel.append(b)}
async function selectWatermark(button){wmCarousel.querySelectorAll('.watermark-item').forEach(x=>x.classList.toggle('selected',x===button));if(button.dataset.watermark==='none'){selectedWatermark=null;return}selectedWatermark={id:button.dataset.watermark,url:button.dataset.url};await openWatermarkEditor()}
wmCarousel.querySelector('[data-watermark="none"]').onclick=()=>selectWatermark(wmCarousel.querySelector('[data-watermark="none"]'));
$('addWatermark').onclick=()=>wmFile.click();wmFile.onchange=async()=>{const f=wmFile.files?.[0];wmFile.value='';if(!f)return;try{$('addWatermark').disabled=true;const processed=await processedWatermark(f),body=new FormData();body.set('image',processed);const r=await fetch('/api/miniapp/watermarks',{method:'POST',headers:authHeaders(),body}),wm=await r.json();if(!r.ok)throw new Error(wm?.error?.message||'Не удалось сохранить водяной знак');await appendWatermark(wm);const b=wmCarousel.querySelector(`[data-watermark="${CSS.escape(wm.id)}"]`);selectWatermark(b)}catch(e){showError(e.message)}finally{$('addWatermark').disabled=false}};
async function openWatermarkEditor(){if(!selectedWatermark)return;const blob=await compositeBlob(),baseUrl=URL.createObjectURL(blob),base=await loadImage(baseUrl),wm=await loadImage(selectedWatermark.url),r=slots.getBoundingClientRect();mode='watermark';editing=null;editSnapshot={...watermarkState};editor.hidden=false;$('editorTitle').textContent='Водяной знак';$('editorHint').textContent='Двигайте водяной знак одним пальцем. Масштабируйте двумя.';editImage.hidden=false;editImage.src=baseUrl;wmImage.hidden=false;wmImage.src=selectedWatermark.url;requestAnimationFrame(()=>{setEditorGeometryFromRect(r);const g=Number(stage.dataset.geometryScale||1);editImage.style.width=`${r.width}px`;editImage.style.height=`${r.height}px`;editImage.style.transform=`translate(-50%,-50%) scale(${g})`;wmImage.style.width=`${wm.naturalWidth}px`;wmImage.style.height=`${wm.naturalHeight}px`;if(watermarkState.scale===1)watermarkState.scale=Math.min(r.width*.35/wm.naturalWidth,r.height*.35/wm.naturalHeight);rotation.value=String(watermarkState.rotation);$('angle').textContent=`${watermarkState.rotation}°`;transform()})}
function showError(m){$('error').textContent=m||''}
$('back').onclick=()=>{if(history.length>1)history.back();else location.replace('/')};$('finish').onclick=()=>history.back();window.addEventListener('beforeunload',()=>{['before','after'].forEach(s=>photos[s]&&URL.revokeObjectURL(photos[s].url));wmCarousel.querySelectorAll('[data-url]').forEach(b=>URL.revokeObjectURL(b.dataset.url))});render();loadWatermarks();
})();