(()=>{
const tg=window.Telegram?.WebApp,text=document.querySelector('#text'),imageInput=document.querySelector('#image'),previews=document.querySelector('#previews'),removeImage=document.querySelector('#remove-image');
if(!tg?.initData||!text||!imageInput)return;
const logs=[];function log(kind,data={}){logs.push({time:new Date().toISOString(),kind,...data});if(logs.length>300)logs.shift();const area=document.querySelector('#cosmo-diagnostics-log');if(area)area.value=logs.map(x=>JSON.stringify(x)).join('\n')}
function mountDiagnostics(){if(document.querySelector('#cosmo-diagnostics'))return;const box=document.createElement('section');box.id='cosmo-diagnostics';box.style.cssText='margin:28px 16px max(24px,env(safe-area-inset-bottom));padding:14px;border:1px solid #bbb;border-radius:14px;background:rgba(128,128,128,.08);font:12px monospace';box.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><b style="font:600 14px system-ui">Диагностика</b><button id="cosmo-diagnostics-copy" type="button">Copy</button></div><textarea id="cosmo-diagnostics-log" readonly style="box-sizing:border-box;width:100%;height:260px;resize:vertical;padding:8px;border:1px solid #bbb;border-radius:8px;background:transparent;color:inherit;font:11px/1.45 monospace"></textarea>';document.body.append(box);box.querySelector('#cosmo-diagnostics-copy').onclick=async e=>{const value=logs.map(x=>JSON.stringify(x)).join('\n');try{await navigator.clipboard.writeText(value);e.currentTarget.textContent='Copied';setTimeout(()=>e.currentTarget.textContent='Copy',1200)}catch{const a=box.querySelector('textarea');a.focus();a.select();document.execCommand('copy')}};log('diagnostics-ready',{href:location.href})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountDiagnostics,{once:true});else mountDiagnostics();
const nativeFetch=window.fetch.bind(window);let requestId=0;window.fetch=async(input,init={})=>{const id=++requestId,url=typeof input==='string'?input:input?.url||String(input),method=(init.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase(),started=performance.now();let body=null;if(init.body instanceof FormData){body={};for(const [k,v] of init.body.entries()){const val=v instanceof File?`[File ${v.name} ${v.size}b]`:String(v);if(k==='images')(body.images??=[]).push(val);else body[k]=val}}log('request',{id,method,url,body});try{const r=await nativeFetch(input,init);log('response',{id,method,url,status:r.status,ok:r.ok,durationMs:Math.round(performance.now()-started)});return r}catch(e){log('request-error',{id,method,url,durationMs:Math.round(performance.now()-started),error:e?.message||String(e)});throw e}};
const auth=()=>({Authorization:`tma ${tg.initData}`});let restoring=true,saveTimer=0,imagesDirty=false,lastPlatform='telegram',restoreGeneration=0;
function platform(){const vk=document.querySelector('.composer-tab[data-platform="vk"],.composer-tab[data-tab="vk"]');return vk?.classList.contains('active')?'vk':'telegram'}
function activeIndex(){const imgs=[...previews.querySelectorAll('img')];const i=imgs.findIndex(x=>x.classList.contains('active'));return i<0?0:i}
async function saveNow(){if(restoring){log('draft-save-skipped',{reason:'restoring'});return}clearTimeout(saveTimer);const body=new FormData();body.set('text',text.value);body.set('platform',platform());body.set('activePhotoIndex',String(activeIndex()));body.set('imagesChanged',imagesDirty?'1':'0');if(imagesDirty)[...imageInput.files].slice(0,10).forEach(f=>body.append('images',f,f.name));log('draft-save-start',{textLength:text.value.length,platform:platform(),activePhotoIndex:activeIndex(),imagesDirty,imageCount:imageInput.files.length});try{const r=await fetch('/api/miniapp/draft',{method:'POST',headers:auth(),body});if(r.ok){imagesDirty=false;log('draft-save-ok',{status:r.status})}else log('draft-save-failed',{status:r.status})}catch(e){log('draft-save-error',{error:e?.message||String(e)});console.warn('Draft save failed',e)}}
function schedule(reason='unknown'){if(restoring){log('draft-schedule-skipped',{reason,restoring:true});return}clearTimeout(saveTimer);log('draft-scheduled',{reason,delayMs:450,imagesDirty});saveTimer=setTimeout(saveNow,450)}
text.addEventListener('input',()=>schedule('text-input'));imageInput.addEventListener('change',()=>{if(restoring)return;imagesDirty=true;schedule('images-change')});
removeImage?.addEventListener('click',()=>{if(restoring)return;setTimeout(()=>{imagesDirty=true;schedule('remove-images')},0)});
document.addEventListener('click',e=>{const tab=e.target.closest?.('.composer-tab');if(tab)setTimeout(()=>schedule('platform-tab'),0);const thumb=e.target.closest?.('#previews img');if(thumb)setTimeout(()=>schedule('active-photo'),350)});
const observer=new MutationObserver(records=>{if(restoring)return;if(records.some(r=>r.type==='attributes'&&r.attributeName==='class'))schedule('preview-class-change')});observer.observe(previews,{subtree:true,attributes:true,attributeFilter:['class']});
document.addEventListener('visibilitychange',()=>{log('visibility',{state:document.visibilityState});if(document.hidden)saveNow()});window.addEventListener('pagehide',()=>{log('pagehide');saveNow()});
function cancelRestore(){restoreGeneration++;restoring=false;log('draft-restore-cancel',{generation:restoreGeneration})}
async function restore(){const generation=++restoreGeneration;log('draft-restore-start',{generation});try{const r=await fetch('/api/miniapp/draft',{headers:auth(),cache:'no-store'});if(generation!==restoreGeneration)return;if(!r.ok){log('draft-restore-failed',{status:r.status});return}const data=await r.json(),d=data?.draft;if(generation!==restoreGeneration||!d){log('draft-restore-empty',{generation});return}log('draft-restore-data',{textLength:(d.text||'').length,platform:d.platform,imageCount:Array.isArray(d.images)?d.images.length:0,activePhotoIndex:d.activePhotoIndex});text.value=d.text||'';text.dispatchEvent(new Event('input',{bubbles:true}));lastPlatform=d.platform||'telegram';const images=Array.isArray(d.images)?d.images:[];if(images.length&&typeof DataTransfer!=='undefined'){const dt=new DataTransfer();for(const item of images){if(generation!==restoreGeneration)return;const ir=await fetch(item.url,{headers:auth(),cache:'no-store'});if(generation!==restoreGeneration)return;if(!ir.ok)continue;const blob=await ir.blob();if(generation!==restoreGeneration)return;dt.items.add(new File([blob],item.fileName||`photo-${item.position+1}`,{type:item.contentType||blob.type||'image/jpeg'}))}if(generation!==restoreGeneration)return;if(dt.files.length){imageInput.files=dt.files;imageInput.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,80));if(generation!==restoreGeneration)return;const thumbs=[...previews.querySelectorAll('img')],idx=Math.min(Math.max(Number(d.activePhotoIndex)||0,0),Math.max(thumbs.length-1,0));thumbs[idx]?.click()}}
if(generation!==restoreGeneration)return;const selector=lastPlatform==='vk'?'.composer-tab[data-platform="vk"],.composer-tab[data-tab="vk"]':'.composer-tab[data-platform="telegram"],.composer-tab[data-tab="telegram"]';document.querySelector(selector)?.click();log('draft-restore-ok',{generation})
}catch(e){log('draft-restore-error',{generation,error:e?.message||String(e)});console.warn('Draft restore failed',e)}finally{if(generation===restoreGeneration)restoring=false}}
window.CosmoSofaDraft={save:saveNow,cancelRestore};
restore();
})();
import('/navigation.js').then(()=>Promise.all([import('/ai-mock-transfer.js'),import('/composer-screen.js'),import('/screen-owner.js'),import('/composer-image-manager.js')])).catch(error=>console.warn('Navigation shell load failed',error));
