(()=>{
const STEPS=['telegram_bot','telegram_group','telegram_preview','vk_group'];
const telegramLogo='<div class="onboarding-logo"><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="32" fill="#2AABEE"/><path fill="#fff" d="M48.2 18.4 42.7 46c-.4 2-1.6 2.5-3.3 1.6l-8.4-6.2-4.1 3.9c-.4.4-.8.8-1.7.8l.6-8.6 15.7-14.2c.7-.6-.1-1-.9-.4L21.2 35.1l-8.3-2.6c-1.8-.6-1.8-1.8.4-2.7l32.5-12.5c1.5-.5 2.8.4 2.4 1.1Z"/></svg></div>';
const groupLogo='<div class="onboarding-logo"><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="32" fill="#2AABEE"/><g transform="translate(8 8) scale(2)"><path fill="#fff" d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z"/></g></svg></div>';
const eyeLogo='<div class="onboarding-logo"><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="32" fill="#2AABEE"/><path fill="#fff" d="M32 20c-8.6 0-15.9 5.3-19 12 3.1 6.7 10.4 12 19 12s15.9-5.3 19-12c-3.1-6.7-10.4-12-19-12Zm0 19a7 7 0 1 1 0-14 7 7 0 0 1 0 14Zm0-11a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/></svg></div>';
const vkLogo='<div class="onboarding-logo"><svg viewBox="0 0 64 64" aria-hidden="true"><rect width="64" height="64" rx="16" fill="#0077FF"/><path fill="#fff" d="M34.8 44C20.2 44 11.9 34 11.5 17.4h7.3c.2 12.2 5.6 17.4 9.8 18.5V17.4h6.9V28c4.1-.4 8.4-5.2 9.9-10.6h6.9c-1.1 6.7-5.9 11.5-9.3 13.5 3.4 1.6 8.8 5.8 10.9 13.1h-7.6c-1.7-5.2-5.6-9.2-10.8-9.7V44h-.7Z"/></svg></div>';
const progress=index=>`<div class="onboarding-progress">${[0,1,2,3,4].map(item=>`<span${item===index?' class="active"':''}></span>`).join('')}</div>`;
const header='<header class="settings-header"><button class="back-button" data-onboarding-back type="button" aria-label="Назад"><span>Назад</span></button><h1>Настройки</h1><span class="header-spacer"></span></header>';
const shell=(step,index,content)=>`<section class="screen settings-screen onboarding-step-screen" data-onboarding-step="${step}" hidden>${header}${progress(index)}${content}</section>`;
class OnboardingView{
  constructor({root,controller,telegram}){if(!root||!controller)throw new TypeError('OnboardingView requires root and controller');this.root=root;this.controller=controller;this.telegram=telegram;this.renderMarkup();this.bind();this.unsubscribe=controller.subscribe(state=>this.render(state));this.resume=()=>{if(controller.getState().status==='waiting_external_return')controller.resume().catch(()=>{})};document.addEventListener('visibilitychange',this.resume);window.addEventListener('focus',this.resume)}
  renderMarkup(){this.root.innerHTML=[
    shell('telegram_bot',0,`<div class="onboarding-hero">${telegramLogo}<h2>Персональный бот</h2><p>Создайте персонального Telegram-бота, через которого Cosmo Sofa будет публиковать ваши материалы.</p></div><section class="onboarding-step-card"><div class="onboarding-state-row"><div><span class="detail-label">Тайтл бота</span><strong data-bot-title>Ещё не создан</strong><span class="detail-label" style="margin-top:8px">Username</span><strong data-bot-username>—</strong></div><span data-bot-badge class="state-badge missing">Не создан</span></div></section><button class="onboarding-primary" data-onboarding-primary>Создать персонального бота</button><button class="onboarding-skip" data-onboarding-skip>Пропустить</button>`),
    shell('telegram_group',1,`<div class="onboarding-hero">${groupLogo}<h2>Группа Telegram</h2><p>Добавьте персонального бота в нужную Telegram-группу и выдайте ему права администратора.</p></div><section class="onboarding-step-card"><div class="onboarding-state-row"><div><span class="detail-label">Персональный бот</span><strong data-group-bot>—</strong></div><span class="state-badge ready">Готов</span></div><div class="onboarding-state-row"><div><span class="detail-label">Группа для публикаций</span><strong data-group-title>Ещё не подключена</strong></div><span data-group-badge class="state-badge missing">Не подключена</span></div></section><button class="onboarding-primary" data-onboarding-primary>Выбрать Telegram-группу</button><button class="onboarding-skip" data-onboarding-skip>Пропустить</button><section class="onboarding-help-card"><h3>Что произойдёт</h3><ol><li>Telegram откроет список групп, куда можно добавить бота.</li><li>Выберите нужную группу и подтвердите добавление.</li><li>После добавления выдайте боту права администратора.</li></ol></section>`),
    shell('telegram_preview',2,`<div class="onboarding-hero">${eyeLogo}<h2>Предпросмотр</h2><p>Используйте личный чат с персональным ботом для проверки публикаций перед отправкой в группу.</p></div><section class="onboarding-step-card"><div class="onboarding-state-row"><div><span class="detail-label">Персональный бот</span><strong data-preview-bot>—</strong></div><span data-preview-badge class="state-badge missing">Не готов</span></div></section><button class="onboarding-primary" data-onboarding-primary>Открыть чат с ботом</button><button class="onboarding-skip" data-onboarding-skip>Пропустить</button>`),
    shell('vk_group',3,`<div class="onboarding-hero">${vkLogo}<h2>Группа ВКонтакте</h2><p>Подключите сообщество, куда хотите публиковать материалы.</p></div><section class="onboarding-step-card"><div class="onboarding-state-row"><div><span class="detail-label">Группа для публикаций</span><strong data-vk-title>Группа не выбрана</strong></div><span data-vk-badge class="state-badge missing">Не подключена</span></div></section><div class="vk-alert-card"><div class="vk-alert-emoji">🔗</div><div><strong>Подключение через VK</strong><p>Откройте VK, выберите сообщество и затем вернитесь в Cosmo Sofa.</p></div></div><button class="onboarding-primary" data-onboarding-primary>Открыть VK</button><button class="onboarding-skip" data-onboarding-skip>Пропустить</button>`)
  ].join('')}
  bind(){this.root.addEventListener('click',event=>{const button=event.target.closest?.('button');if(!button)return;if(button.matches('[data-onboarding-back]'))this.controller.back();else if(button.matches('[data-onboarding-skip]'))this.act(()=>this.controller.skip());else if(button.matches('[data-onboarding-primary]'))this.act(()=>this.primary())});for(const screen of this.root.querySelectorAll('[data-onboarding-step]'))this.bindSwipe(screen)}
  primary(){const step=this.controller.getState().step;if(step==='telegram_bot')return this.controller.prepareManagedBot();if(step==='telegram_group')return this.controller.connectTelegramGroup();if(step==='telegram_preview')return this.controller.openPreview();if(step==='vk_group')return this.controller.connectVk()}
  async act(action){try{await action()}catch(error){this.telegram?.showAlert(error instanceof Error?error.message:'Не удалось выполнить действие.')}}
  bindSwipe(screen){let x=0,y=0,dx=0,tracking=false,horizontal=false;screen.addEventListener('touchstart',event=>{const touch=event.touches[0];x=touch.clientX;y=touch.clientY;dx=0;tracking=true;horizontal=false},{passive:true});screen.addEventListener('touchmove',event=>{if(!tracking)return;const touch=event.touches[0],mx=touch.clientX-x,my=touch.clientY-y;if(!horizontal){if(Math.abs(mx)<12)return;if(Math.abs(mx)<=Math.abs(my)*1.8){tracking=false;return}horizontal=true}dx=mx;screen.style.transform=`translate3d(${dx}px,0,0)`;event.preventDefault()},{passive:false});screen.addEventListener('touchend',()=>{screen.style.transform='';if(tracking&&horizontal&&Math.abs(dx)>=Math.max(120,Math.min(180,(innerWidth||360)*.35))){if(dx>0)this.controller.back();else this.controller.next()}tracking=false},{passive:true})}
  text(selector,value){const element=this.root.querySelector(selector);if(element)element.textContent=value}
  badge(selector,ready,yes,no){const element=this.root.querySelector(selector);if(element){element.textContent=ready?yes:no;element.className=`state-badge ${ready?'ready':'missing'}`}}
  render(state){for(const screen of this.root.querySelectorAll('[data-onboarding-step]'))screen.hidden=screen.dataset.onboardingStep!==state.step;const account=state.account||{},bot=account.managedBot,botName=bot?.displayName||'Ещё не создан',username=bot?.username?`@${bot.username}`:'—',group=bot?.destination?.chatTitle||'Ещё не подключена',groupReady=!!bot?.destination?.connected,previewReady=!!account.previewReady,vk=account.vkGroup?.connected?account.vkGroup:null,vkUrl=vk?(vk.screenName?`vk.com/${vk.screenName}`:vk.groupUrl||''):'';this.text('[data-bot-title]',botName);this.text('[data-bot-username]',username);this.badge('[data-bot-badge]',!!bot,'Готов','Не создан');this.text('[data-group-bot]',bot?`${botName} · ${username}`:'—');this.text('[data-group-title]',group);this.badge('[data-group-badge]',groupReady,'Подключена','Не подключена');this.text('[data-preview-bot]',bot?botName:'Ещё не создан');this.badge('[data-preview-badge]',previewReady,'Готов','Не готов');this.text('[data-vk-title]',vk?(vk.groupName&&vkUrl?`${vk.groupName} · ${vkUrl}`:vk.groupName||vkUrl):'Группа не выбрана');this.badge('[data-vk-badge]',!!vk,'Подключена','Не подключена');const busy=state.status==='loading'||state.status==='submitting';for(const button of this.root.querySelectorAll('button'))button.disabled=busy;window.scrollTo({top:0,behavior:'instant'})}
  dispose(){this.unsubscribe?.();document.removeEventListener('visibilitychange',this.resume);window.removeEventListener('focus',this.resume)}
}
window.CosmoOnboardingView=Object.freeze({OnboardingView,create:options=>new OnboardingView(options)});
})();
