(()=>{
const $=s=>document.querySelector(s),tg=window.Telegram?.WebApp;
const ids=['tg-bot-screen','tg-group-screen','tg-preview-screen','vk-group-screen'];
const screens=()=>ids.map(id=>document.getElementById(id)).filter(Boolean);
function show(screen){const settings=$('#settings-screen');if(settings)settings.hidden=true;for(const item of screens())item.hidden=item!==screen;screen.hidden=false;window.scrollTo(0,0);tg?.HapticFeedback?.selectionChanged?.()}
function backSettings(){for(const item of screens())item.hidden=true;const settings=$('#settings-screen');if(settings)settings.hidden=false;window.scrollTo(0,0);tg?.HapticFeedback?.selectionChanged?.()}
function addSkip(screen,index){if(screen.querySelector('.onboarding-skip'))return;const primary=screen.querySelector('.onboarding-primary');if(!primary)return;const button=document.createElement('button');button.type='button';button.className='onboarding-skip';button.textContent='Пропустить';button.addEventListener('click',()=>{const list=screens(),current=list.indexOf(screen),next=list[current+1];if(next)show(next);else backSettings()});primary.insertAdjacentElement('afterend',button)}
function addSwipe(screen){if(screen.dataset.swipeReady==='1')return;screen.dataset.swipeReady='1';let x=0,y=0,dx=0,tracking=false,horizontal=false;const reset=()=>{screen.style.transition='transform 180ms ease-out';screen.style.transform='translate3d(0,0,0)';setTimeout(()=>{screen.style.transition='';screen.style.transform=''},190)};const commit=(dir,nav)=>{const w=Math.max(innerWidth||0,screen.clientWidth||0,320);screen.style.transition='transform 180ms ease-out';screen.style.transform=`translate3d(${dir*w}px,0,0)`;setTimeout(()=>{screen.style.transition='';screen.style.transform='';nav()},180)};screen.addEventListener('touchstart',e=>{const t=e.touches[0];x=t.clientX;y=t.clientY;dx=0;tracking=true;horizontal=false;screen.style.transition='none'},{passive:true});screen.addEventListener('touchmove',e=>{if(!tracking)return;const t=e.touches[0],mx=t.clientX-x,my=t.clientY-y;if(!horizontal){if(Math.abs(mx)<12)return;if(Math.abs(mx)<=Math.abs(my)*1.8){tracking=false;reset();return}horizontal=true}dx=mx;screen.style.transform=`translate3d(${dx}px,0,0)`;e.preventDefault()},{passive:false});screen.addEventListener('touchend',()=>{if(!tracking||!horizontal){tracking=false;return reset()}const list=screens(),i=list.indexOf(screen),prev=list[i-1],next=list[i+1],nav=dx>0?(prev?()=>show(prev):backSettings):(next?()=>show(next):null),threshold=Math.max(120,Math.min(180,(innerWidth||screen.clientWidth||360)*.35));if(Math.abs(dx)>=threshold&&nav)commit(dx>0?1:-1,nav);else reset();tracking=false},{passive:true});screen.addEventListener('touchcancel',()=>{tracking=false;reset()},{passive:true})}
function init(){screens().forEach((screen,index)=>{addSkip(screen,index);addSwipe(screen)})}
init();setTimeout(init,0);setTimeout(init,500);
})();