(()=>{
const tg=window.Telegram?.WebApp;if(!tg?.initData)return;
const $=s=>document.querySelector(s),auth=()=>({Authorization:`tma ${tg.initData}`});
const userId=String(tg.initDataUnsafe?.user?.id||'telegram');
const seenKey=`cosmo-sofa:onboarding-seen:${userId}`;
function hideOnboarding(){document.querySelectorAll('.onboarding-step-screen').forEach(s=>s.hidden=true);const settings=$('#settings-screen');if(settings)settings.hidden=true}
function showHome(){hideOnboarding();const home=$('#home-screen'),ai=$('#ai-screen'),composer=$('#composer-screen');if(home)home.hidden=false;if(ai)ai.hidden=true;if(composer)composer.hidden=true;scrollTo({top:0,behavior:'instant'})}
function modal(title,buttonLabel,onContinue){document.querySelector('#cosmo-onboarding-modal')?.remove();const overlay=document.createElement('div');overlay.id='cosmo-onboarding-modal';overlay.style.cssText='position:fixed;inset:0;z-index:20000;background:rgba(0,0,0,.48);display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box';const card=document.createElement('div');card.style.cssText='width:min(100%,460px);background:var(--tg-theme-bg-color,#fff);color:var(--tg-theme-text-color,#111);border-radius:24px;padding:28px 22px 22px;box-sizing:border-box;text-align:center;box-shadow:0 18px 50px rgba(0,0,0,.28)';const heading=document.createElement('strong');heading.textContent=title;heading.style.cssText='display:block;font:800 22px/1.3 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif;text-transform:uppercase;margin:0 0 22px';const button=document.createElement('button');button.type='button';button.textContent=buttonLabel;button.style.cssText='width:100%;border:0;border-radius:13px;padding:15px 16px;background:var(--tg-theme-button-color,#2481cc);color:var(--tg-theme-button-text-color,#fff);font:700 16px/1.2 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif';button.onclick=()=>{overlay.remove();tg.HapticFeedback?.selectionChanged?.();onContinue?.()};card.append(heading,button);overlay.append(card);document.body.append(overlay)}
async function state(){try{const r=await fetch('/api/miniapp/me',{headers:auth(),cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function initialRoute(){const data=await state();if(!data)return;const empty=!data.managedBot&&!data.vkGroup?.connected;const seen=localStorage.getItem(seenKey)==='1';showHome();if(seen||!empty){if(!seen)localStorage.setItem(seenKey,'1');return}localStorage.setItem(seenKey,'1');modal('Настройте программу в несколько шагов','Продолжить',()=>{$('#edit-personal-bot')?.click()})}
let managedBotKnown=null;async function refreshManaged(){const data=await state();managedBotKnown=data?.managedBot||null;return managedBotKnown}
document.addEventListener('click',async event=>{const groupButton=event.target.closest?.('#choose-tg-group,#open-tg-group,#edit-tg-group');if(!groupButton)return;const bot=managedBotKnown||await refreshManaged();if(bot)return;event.preventDefault();event.stopImmediatePropagation();modal('Сначала создайте личного бота','Продолжить',()=>{$('#edit-personal-bot')?.click()})},true);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refreshManaged()});window.addEventListener('focus',()=>void refreshManaged());
setTimeout(()=>{void refreshManaged();void initialRoute()},180);
})();
