(()=>{
const $=selector=>document.querySelector(selector),settings=$('#settings-screen'),controller=window.CosmoOnboardingControllerInstance;
if(!settings||!controller)return;
const editSvg='<svg viewBox="0 0 24 24"><path fill="currentColor" d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25ZM20.71 7.04a.996.996 0 0 0 0-1.41l-2.34-2.34a.996.996 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83Z"/></svg>';
function addEdit(value,id,label){const row=value?.closest('.settings-item')?.querySelector('.settings-row'),dot=row?.querySelector('.status-dot');let button=$('#'+id);if(row&&!button){button=document.createElement('button');button.id=id;button.className='row-edit-button';button.type='button';button.setAttribute('aria-label',label);button.innerHTML=editSvg;row.insertBefore(button,dot)}return{button,dot,status:row?.querySelector('.settings-copy span')}}
const botUi=addEdit($('#settings-bot-value'),'edit-personal-bot','Создать или сменить персонального бота'),previewUi=addEdit($('#settings-preview-value'),'edit-preview','Настроить предпросмотр'),vkUi=addEdit($('#settings-vk-group-value'),'edit-vk-group','Добавить или сменить группу ВКонтакте'),groupUi={button:$('#edit-tg-group'),dot:$('#settings-tg-group-dot'),status:$('#settings-tg-group-status')};
function text(selector,value){const element=$(selector);if(element)element.textContent=value}
function dot(ui,ready,yes='Подключена',no='Не подключена'){if(ui.dot)ui.dot.className=`status-dot ${ready?'ok':'error'}`;if(ui.status)ui.status.textContent=ready?yes:no}
function render(account){if(!account)return;const bot=account.managedBot,botReady=!!bot,groupReady=!!bot?.destination?.connected,previewReady=!!account.previewReady,vk=account.vkGroup?.connected?account.vkGroup:null,vkUrl=vk?(vk.screenName?`vk.com/${vk.screenName}`:vk.groupUrl||''):'';text('#settings-bot-value',botReady?`${bot.displayName||'Персональный бот'} · ${bot.username?`@${bot.username}`:'—'}`:'Не создан');text('#settings-tg-group-value',groupReady?bot.destination.chatTitle||'Telegram-группа':'Не подключена');text('#settings-preview-value',previewReady?'Личный чат с ботом':'Не настроен');text('#settings-vk-group-value',vk?(vk.groupName&&vkUrl?`${vk.groupName} · ${vkUrl}`:vk.groupName||vkUrl):'Не подключена');dot(botUi,botReady);dot(groupUi,groupReady);dot(previewUi,previewReady,'Настроен','Не настроен');dot(vkUi,!!vk)}
controller.subscribe(state=>render(state.account));controller.refresh().catch(()=>{});
function edit(step){return()=>window.CosmoRouter.openOnboarding({mode:'edit',initialStep:step,returnTo:'settings'})}
botUi.button?.addEventListener('click',edit('telegram_bot'));groupUi.button?.addEventListener('click',edit('telegram_group'));previewUi.button?.addEventListener('click',edit('telegram_preview'));vkUi.button?.addEventListener('click',edit('vk_group'));
})();
