import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const accountSource=await readFile(new URL('./account-state.js',import.meta.url),'utf8');
const selectionSource=await readFile(new URL('./vk-destination-selection.js',import.meta.url),'utf8');
const composerSource=await readFile(new URL('./composer-vk-destination.js',import.meta.url),'utf8');
const settingsSource=await readFile(new URL('./settings.js',import.meta.url),'utf8');
const bootstrapSource=await readFile(new URL('./bootstrap.js',import.meta.url),'utf8');
const appSource=await readFile(new URL('./app.js',import.meta.url),'utf8');
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}}
function response(data,{ok=true,status=200}={}){return{ok,status,json:async()=>data}}
function loadFactory(source,name){const window={};vm.runInNewContext(source,{window,document:{querySelector:()=>null},console,Promise});return window[name]}
function createAccountHarness(){const telegramEvents=new Map(),windowEvents=new Map(),documentEvents=new Map(),requests=[];const window={Telegram:{WebApp:{initData:'signed',onEvent:(name,handler)=>telegramEvents.set(name,handler)}},addEventListener:(name,handler)=>windowEvents.set(name,handler)};const document={visibilityState:'visible',addEventListener:(name,handler)=>documentEvents.set(name,handler)};const fetch=()=>{const request=deferred();requests.push(request);return request.promise};vm.runInNewContext(accountSource,{window,document,fetch,console,Set,Promise});return{store:window.CosmoAccountState,requests,telegramEvents,windowEvents,documentEvents}}
async function tick(){await Promise.resolve();await Promise.resolve()}
test('post-external-return refresh waits for a stale in-flight request and coalesces resume signals',async()=>{const h=createAccountHarness();const old=h.store.refresh();h.store.expectExternalReturn();h.telegramEvents.get('activated')();h.windowEvents.get('focus')();h.documentEvents.get('visibilitychange')();assert.equal(h.requests.length,1);h.requests[0].resolve(response({vkGroup:{connected:false}}));await old;await tick();assert.equal(h.requests.length,2);h.requests[1].resolve(response({vkGroup:{connected:true,groupName:'Салон'}}));await h.store.refreshAfterCurrent();assert.equal(h.store.getSnapshot().vkGroup.connected,true)});
test('shared VK selection coalesces clicks, opens the handoff, and arms factual refresh',async()=>{const factory=loadFactory(selectionSource,'CosmoVkDestinationSelectionFactory');const request=deferred(),opened=[],events=[];const selection=factory.create({api:{createVkHandoff:()=>request.promise},telegram:{notifySelection:()=>events.push('haptic'),openExternalLink:url=>opened.push(url)},accountState:{expectExternalReturn:()=>{events.push('expected');return()=>events.push('cancelled')}}});const first=selection.open(),second=selection.open();assert.equal(first,second);request.resolve({vkUrl:'https://vk.example/select'});await first;assert.deepEqual(opened,['https://vk.example/select']);assert.deepEqual(events,['expected','haptic'])});
test('shared VK selection reports API, malformed handoff, and external-open failures locally',async()=>{const factory=loadFactory(selectionSource,'CosmoVkDestinationSelectionFactory');await assert.rejects(factory.create({api:{createVkHandoff:async()=>{throw new Error('API error')}}}).open(),/API error/);await assert.rejects(factory.create({api:{createVkHandoff:async()=>({})}}).open(),/Не удалось открыть выбор группы/);let cancelled=0;await assert.rejects(factory.create({api:{createVkHandoff:async()=>({vkUrl:'https://vk.example'})},telegram:{openExternalLink(){throw new Error('unsupported')}},accountState:{expectExternalReturn:()=>()=>cancelled++}}).open(),/unsupported/);assert.equal(cancelled,1)});
function composerHarness(initial){const factory=loadFactory(composerSource,'CosmoComposerVkDestinationFactory');let account=initial;const subscribers=[],calls=[];const view={showSelection:()=>calls.push(['selection']),showSuccess:group=>calls.push(['success',group.groupName]),setBusy:value=>calls.push(['busy',value]),setError:value=>calls.push(['error',value]),close:()=>calls.push(['close'])};const accountState={getSnapshot:()=>account,refresh:async()=>account,subscribe:fn=>{subscribers.push(fn);return()=>{}}};const selection={open:async()=>{calls.push(['open'])}};const controller=factory.create({accountState,selection,view});return{controller,calls,setAccount(value){account=value;for(const fn of subscribers)fn(value)}}}
test('Composer lets a connected account use existing publication',async()=>{const h=composerHarness({vkGroup:{connected:true}});let count=0;await h.controller.requestPublication(()=>count++);assert.equal(count,1);assert.deepEqual(h.calls,[])});
test('Composer requires factual confirmation and explicit Continue before one publication',async()=>{const h=composerHarness({vkGroup:{connected:false}});let count=0;await h.controller.requestPublication(()=>count++);assert.deepEqual(h.calls,[['selection']]);await Promise.all([h.controller.select(),h.controller.select()]);assert.equal(h.calls.filter(x=>x[0]==='open').length,1);h.setAccount({vkGroup:{connected:true,groupName:'Салон'}});assert.equal(count,0);assert.ok(h.calls.some(x=>x[0]==='success'));await Promise.all([h.controller.continuePublication(),h.controller.continuePublication()]);assert.equal(count,1)});
test('Composer cancellation and return without selection never publish',async()=>{const h=composerHarness({vkGroup:{connected:false}});let count=0;await h.controller.requestPublication(()=>count++);await h.controller.select();h.setAccount({vkGroup:{connected:false}});assert.equal(h.calls.some(x=>x[0]==='success'),false);h.controller.cancel();await h.controller.continuePublication();assert.equal(count,0)});
test('Composer ignores account completion after navigation cancellation',async()=>{const factory=loadFactory(composerSource,'CosmoComposerVkDestinationFactory');const pending=deferred(),calls=[];const view={showSelection:()=>calls.push('selection'),showSuccess(){},setBusy(){},setError(){},close:()=>calls.push('close')};const controller=factory.create({accountState:{getSnapshot:()=>null,refresh:()=>pending.promise,subscribe:()=>()=>{}},selection:{open:async()=>{}},view});const request=controller.requestPublication(()=>calls.push('publish'));controller.cancel();pending.resolve({vkGroup:{connected:false}});await request;assert.deepEqual(calls,['close'])});
test('Settings states and both actions use shared operation directly',()=>{assert.match(settingsSource,/'Не выбрана'/);assert.match(settingsSource,/vk\?'Сменить':'Выбрать'/);assert.match(settingsSource,/CosmoVkDestinationSelection\.open\(\)/);assert.doesNotMatch(settingsSource,/openOnboarding[\s\S]*vk_group/)});
test('only app owns publish click and obsolete guard is absent',()=>{assert.match(appSource,/CosmoComposerVkDestination/);assert.doesNotMatch(bootstrapSource,/vk-group-publish-guard/);assert.match(bootstrapSource,/composer-vk-destination/)});
