import {AppError,type Env} from '../types';
import {validateTelegramMiniAppInitData} from './telegram-miniapp-auth';
import {resolveOrCreateTelegramIdentity} from './telegram-identity';
import {getManagedBotStateForUser} from './managed-bot-onboarding';

type Action='telegram_preview'|'telegram_publish';
type WaitingFor='telegram_bot'|'telegram_preview'|'telegram_group'|'confirmation';
type IntentRow={user_id:string;action:Action;draft_ref:string|null;return_screen:string;waiting_for:WaitingFor;status:string;created_at:string;updated_at:string;expires_at:string};
const TTL_SECONDS=24*60*60;
function initDataFrom(request:Request){return request.headers.get('authorization')?.match(/^tma\s+(.+)$/i)?.[1]??''}
async function account(request:Request,env:Env){const validated=await validateTelegramMiniAppInitData(initDataFrom(request),env.TELEGRAM_BOT_TOKEN);return resolveOrCreateTelegramIdentity(env,String(validated.user.id))}
async function previewReady(env:Env,userId:string){const value=await env.DB.prepare("SELECT 1 AS ready FROM telegram_managed_bot_private_chats pc JOIN telegram_managed_bots mb ON mb.telegram_bot_id=pc.telegram_bot_id AND mb.user_id=pc.user_id AND mb.status='active' WHERE pc.user_id=? AND pc.status='active' LIMIT 1").bind(userId).first<{ready:number}>();return value?.ready===1}
async function event(env:Env,userId:string,action:Action,name:string,waitingFor?:WaitingFor){await env.DB.prepare('INSERT INTO user_onboarding_intent_event(user_id,action,event,waiting_for) VALUES(?,?,?,?)').bind(userId,action,name,waitingFor??null).run()}
async function row(env:Env,userId:string){return env.DB.prepare("SELECT user_id,action,draft_ref,return_screen,waiting_for,status,created_at,updated_at,expires_at FROM user_onboarding_intent WHERE user_id=? AND status='pending' AND expires_at>CURRENT_TIMESTAMP").bind(userId).first<IntentRow>()}
function publicIntent(value:IntentRow|null){return value?{action:value.action,draftRef:value.draft_ref,returnScreen:value.return_screen,waitingFor:value.waiting_for,status:value.status,createdAt:value.created_at,updatedAt:value.updated_at,expiresAt:value.expires_at}:null}
export function reconcileIntent(intent:IntentRow|null,capabilities:{botReady:boolean;groupReady:boolean;previewReady:boolean}){if(!intent)return{decision:'idle' as const,reason:'no_pending_intent'};if(!capabilities.botReady)return{decision:'continue_bot' as const,reason:'telegram_bot_missing',waitingFor:'telegram_bot' as const};if(intent.action==='telegram_preview'&&!capabilities.previewReady)return{decision:'continue_preview_activation' as const,reason:'telegram_preview_chat_missing',waitingFor:'telegram_preview' as const};if(intent.action==='telegram_preview')return{decision:'resume_preview' as const,reason:'telegram_preview_ready',waitingFor:'confirmation' as const};if(!capabilities.groupReady)return{decision:'continue_group' as const,reason:'telegram_group_missing',waitingFor:'telegram_group' as const};return{decision:'show_publish_confirmation' as const,reason:'telegram_requirements_ready',waitingFor:'confirmation' as const}}
async function reconcileFor(env:Env,userId:string,intent:IntentRow|null){const [managed,preview]=await Promise.all([getManagedBotStateForUser(env,userId),previewReady(env,userId)]);const capabilities={botReady:!!managed?.botId,groupReady:!!managed?.chatId,previewReady:preview};const decision=reconcileIntent(intent,capabilities);if(intent&&'waitingFor'in decision&&decision.waitingFor!==intent.waiting_for){await env.DB.prepare('UPDATE user_onboarding_intent SET waiting_for=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?').bind(decision.waitingFor,userId).run();await event(env,userId,intent.action,'transition',decision.waitingFor);intent={...intent,waiting_for:decision.waitingFor}}
return{intent:publicIntent(intent),account:{telegramBot:capabilities.botReady,telegramPreview:capabilities.previewReady,telegramGroup:capabilities.groupReady},reconciliation:{decision:decision.decision,reason:decision.reason}}}
export async function createOnboardingIntent(request:Request,env:Env){const user=await account(request,env);const body=await request.json().catch(()=>{throw new AppError('INVALID_JSON','Некорректный JSON',400)}) as {action?:unknown;draftRef?:unknown};const action=body.action;if(action!=='telegram_preview'&&action!=='telegram_publish')throw new AppError('INVALID_ONBOARDING_INTENT','Неизвестное действие',400);const [managed,preview]=await Promise.all([getManagedBotStateForUser(env,user.userId),previewReady(env,user.userId)]);const waitingFor:WaitingFor=!managed?.botId?'telegram_bot':action==='telegram_preview'&&!preview?'telegram_preview':action==='telegram_publish'&&!managed?.chatId?'telegram_group':'confirmation';const draftRef=typeof body.draftRef==='string'&&body.draftRef.trim()?body.draftRef.trim().slice(0,128):null;await env.DB.prepare("INSERT INTO user_onboarding_intent(user_id,action,draft_ref,return_screen,waiting_for,status,created_at,updated_at,expires_at) VALUES(?,?,?,'composer',?,'pending',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,datetime('now',?)) ON CONFLICT(user_id) DO UPDATE SET action=excluded.action,draft_ref=excluded.draft_ref,return_screen='composer',waiting_for=excluded.waiting_for,status='pending',created_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,expires_at=excluded.expires_at").bind(user.userId,action,draftRef,waitingFor,`+${TTL_SECONDS} seconds`).run();await event(env,user.userId,action,'intent_created',waitingFor);return reconcileFor(env,user.userId,await row(env,user.userId))}
export async function getOnboardingFlow(request:Request,env:Env){const user=await account(request,env);return reconcileFor(env,user.userId,await row(env,user.userId))}
export async function completeOnboardingIntent(request:Request,env:Env){const user=await account(request,env);const intent=await row(env,user.userId);if(intent){await env.DB.prepare("UPDATE user_onboarding_intent SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(user.userId).run();await event(env,user.userId,intent.action,'completed',intent.waiting_for)}return{ok:true}}
export async function cancelOnboardingIntent(request:Request,env:Env){const user=await account(request,env);const intent=await row(env,user.userId);if(intent){await env.DB.prepare("UPDATE user_onboarding_intent SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(user.userId).run();await event(env,user.userId,intent.action,'cancelled',intent.waiting_for)}return{ok:true}}
export async function getOnboardingDiagnostics(request:Request,env:Env){const user=await account(request,env),flow=await reconcileFor(env,user.userId,await row(env,user.userId));const events=await env.DB.prepare('SELECT action,event,waiting_for AS waitingFor,created_at AS createdAt FROM user_onboarding_intent_event WHERE user_id=? ORDER BY id DESC LIMIT 10').bind(user.userId).all();return{...flow,events:events.results||[]}}
