import type {Metadata,Platform,PublicationResult,PostSummary} from '../../../shared/contracts';import type {Env} from '../types';
export async function findOrCreate(env:Env,userId:string,key:string,text:string,m:Metadata={}){key=`${userId}:${key}`;const old=await env.DB.prepare('SELECT id,text FROM posts WHERE idempotency_key=? AND user_id=?').bind(key,userId).first<{id:number;text:string}>();if(old){if(old.text!==text)throw new Error('Идентификатор запроса уже использован с другим текстом');return old.id}const r=await env.DB.prepare('INSERT INTO posts(idempotency_key,title,topic,summary,content_type,text,user_id) VALUES(?,?,?,?,?,?,?)').bind(key,m.title??null,m.topic??null,m.summary??null,m.content_type??null,text,userId).run();return Number(r.meta.last_row_id)}
export async function publication(env:Env,postId:number,p:Platform){return env.DB.prepare('SELECT status,external_post_id,external_url,error_message FROM publications WHERE post_id=? AND platform=?').bind(postId,p).first<any>()}
export async function pending(env:Env,postId:number,p:Platform){await env.DB.prepare(`INSERT INTO publications(post_id,platform,status) VALUES(?,?,'pending') ON CONFLICT(post_id,platform) DO UPDATE SET status='pending',error_message=NULL WHERE status!='published'`).bind(postId,p).run()}
export async function finish(env:Env,postId:number,p:Platform,result:PublicationResult){await env.DB.prepare('UPDATE publications SET status=?,external_post_id=?,external_url=?,error_message=?,published_at=CASE WHEN ?=\'published\' THEN CURRENT_TIMESTAMP ELSE published_at END WHERE post_id=? AND platform=?').bind(result.status,result.external_id??null,result.url??null,result.error??null,result.status,postId,p).run();if(result.status==='published')await env.DB.prepare('UPDATE posts SET published_at=COALESCE(published_at,CURRENT_TIMESTAMP) WHERE id=?').bind(postId).run()}
const select=`SELECT p.*, json_group_array(json_object('platform',u.platform,'status',u.status,'external_id',u.external_post_id,'url',u.external_url,'error',u.error_message)) pubs FROM posts p LEFT JOIN publications u ON u.post_id=p.id`;
function shape(r:any,origin:string):PostSummary{const pubs:Record<string,PublicationResult>={};for(const x of JSON.parse(r.pubs||'[]'))if(x.platform)pubs[x.platform]={status:x.status,external_id:x.external_id??undefined,url:x.url??undefined,error:x.error??undefined};return {...r,image_url:r.image_key?`${origin}/api/images/${encodeURIComponent(r.image_key)}`:null,publications:pubs}}
export async function list(env:Env,userId:string,url:URL,origin:string){const page=Math.max(1,Number(url.searchParams.get('page'))||1),size=Math.min(100,Math.max(1,Number(url.searchParams.get('page_size'))||20)),q=url.searchParams.get('search')?.trim();const where=q?' WHERE p.user_id=? AND (p.title LIKE ? OR p.topic LIKE ? OR p.summary LIKE ? OR p.text LIKE ?)':' WHERE p.user_id=?';const binds=q?[userId,...Array(4).fill(`%${q}%`)]:[userId];const total=await env.DB.prepare(`SELECT count(*) n FROM posts p${where}`).bind(...binds).first<{n:number}>();const rows=await env.DB.prepare(`${select}${where} GROUP BY p.id ORDER BY COALESCE(p.published_at,p.created_at) DESC LIMIT ? OFFSET ?`).bind(...binds,size,(page-1)*size).all<any>();return {items:rows.results.map(r=>shape(r,origin)),page,page_size:size,total:total?.n??0}}
export async function detail(env:Env,userId:string,id:number,origin:string){const r=await env.DB.prepare(`${select} WHERE p.id=? AND p.user_id=? GROUP BY p.id`).bind(id,userId).first<any>();return r?shape(r,origin):null}
export async function history(env:Env){const r=await env.DB.prepare('SELECT date(published_at) date,content_type,COALESCE(topic,title) topic,summary FROM posts WHERE published_at IS NOT NULL ORDER BY published_at DESC LIMIT 300').all<any>();return formatHistory(r.results)}
export function formatHistory(rows:any[]){return `COSMETOLOGY PUBLISHED CONTENT HISTORY\n\nPurpose:\nThis document lists previously published content.\nAvoid proposing topics that substantially duplicate these topics/aspects.\n\n${rows.map(r=>`---\n\nDATE: ${r.date}\nTYPE: ${r.content_type||'unspecified'}\nTOPIC: ${r.topic||'Без темы'}\nSUMMARY:\n${r.summary||'Краткое описание не указано.'}\n`).join('\n')}---\n`}
