import type {Env} from '../types';import {AppError} from '../types';import {renderTelegram,type TelegramRender} from '../../../shared/telegram-renderer';import {isPostDocument} from '../../../shared/post-document';
const RICH_PREFIX='\u2063COSMO_RICH_V1:';
const RETURN_INSTRUCTION_TEXT='Вернитесь в список чатов\nНажмите «Открыть»';
const VK_VPN_CARD_URL='https://raw.githubusercontent.com/buropotok/cosmetology/main/miniapp/assets/vk-publish-vpn.jpg';
export type TelegramPhotoLayout='slideshow'|'collage';
function decodeMiniAppRich(value:string):TelegramRender|string{if(!value.startsWith(RICH_PREFIX)){console.log(JSON.stringify({event:'telegram_rich_decode',hasPrefix:false,inputLength:value.length}));return value}try{const parsed=JSON.parse(value.slice(RICH_PREFIX.length));const valid=isPostDocument(parsed);console.log(JSON.stringify({event:'telegram_rich_post_document',valid,schemaVersion:parsed?.schemaVersion??null,blocks:parsed?.blocks??null}));if(!valid)throw new Error('invalid post document');const rendered=renderTelegram(parsed);console.log(JSON.stringify({event:'telegram_rich_render_result',legacyBlocks:rendered.blocks,richMessageHtml:rendered.richMessageHtml??null,plainText:rendered.plainText,html:rendered.html}));return rendered}catch(error){console.error(JSON.stringify({event:'telegram_rich_decode_error',error:error instanceof Error?error.message:String(error)}));throw new AppError('INVALID_RICH_TEXT','Некорректное форматирование публикации',400)}}
function redactTelegramCredential(value:string,token:string,url:string){return value.split(url).join('[REDACTED]').split(token).join('[REDACTED]')}
async function callWithToken(token:string,method:string,body?:FormData){const url=`https://api.telegram.org/bot${token}/${method}`;const init:RequestInit={method:'POST'};if(body!==undefined)init.body=body;let response:Response;try{response=await fetch(url,init)}catch(error){const errorMessage=error instanceof Error?error.message:String(error);console.error({event:'telegram_bot_api_transport_error',method,errorName:error instanceof Error?error.name:null,errorMessage:redactTelegramCredential(errorMessage,token,url)});throw new AppError('TELEGRAM_ERROR','Не удалось выполнить запрос к Telegram',502)}const responseText=await response.text();let json:any;try{json=JSON.parse(responseText)}catch{console.error({event:'telegram_bot_api_response_parse_error',method,httpStatus:response.status,contentType:response.headers.get('content-type'),responseLength:responseText.length});throw new AppError('TELEGRAM_ERROR',`Telegram API: HTTP ${response.status}; method=${method}; ответ не является JSON`,502)}if(!response.ok||!json?.ok){const description=typeof json?.description==='string'?redactTelegramCredential(json.description,token,url):null,errorCode=json?.error_code??response.status;console.error({event:'telegram_bot_api_error',method,httpStatus:response.status,errorCode,description});const details=[`HTTP ${response.status}`,`method=${method}`,`error_code=${errorCode}`,description?`description=${description}`:null].filter(Boolean).join('; ');throw new AppError('TELEGRAM_ERROR',`Telegram API error: ${details}`,502)}console.log(JSON.stringify({event:'telegram_bot_api_success',method,messageId:json?.result?.message_id??null,hasRichMessage:!!json?.result?.rich_message,richMessage:json?.result?.rich_message??null}));return json.result}
async function call(env:Env,method:string,body?:FormData){return callWithToken(env.TELEGRAM_BOT_TOKEN,method,body)}function url(chat:string,id:number){return chat.startsWith('@')?`https://t.me/${chat.slice(1)}/${id}`:undefined}
function returnInstructionImageUrl(miniAppUrl:string){return new URL('/assets/return-to-app.jpg',miniAppUrl).toString()}
async function removeLegacyReplyKeyboardWithToken(token:string,chatId:string){const body=new FormData();body.set('chat_id',chatId);body.set('text','\u2063');body.set('reply_markup',JSON.stringify({remove_keyboard:true}));const message=await callWithToken(token,'sendMessage',body);if(message?.message_id!=null){const cleanup=new FormData();cleanup.set('chat_id',chatId);cleanup.set('message_id',String(message.message_id));try{await callWithToken(token,'deleteMessage',cleanup)}catch(error){console.warn({event:'telegram_reply_keyboard_cleanup_delete_failed',chatId,errorCode:error instanceof AppError?error.code:'UNKNOWN'})}}}
async function sendReturnInstructionWithToken(token:string,chatId:string,miniAppUrl:string){await removeLegacyReplyKeyboardWithToken(token,chatId);const body=new FormData();body.set('chat_id',chatId);body.set('photo',returnInstructionImageUrl(miniAppUrl));body.set('caption',RETURN_INSTRUCTION_TEXT);return callWithToken(token,'sendPhoto',body)}
export async function sendTelegramText(env:Env,chatId:string,text:string){const body=new FormData();body.set('chat_id',chatId);body.set('text',text);return call(env,'sendMessage',body)}
export async function sendTelegramMiniAppButton(env:Env,chatId:string,url:string){return sendReturnInstructionWithToken(env.TELEGRAM_BOT_TOKEN,chatId,url)}
export async function sendTelegramReturnToAppWithToken(token:string,chatId:string,miniAppUrl:string|undefined){const url=miniAppUrl?.trim();if(!url)throw new AppError('MINIAPP_URL_MISSING','Не настроен URL Mini App',500);return sendReturnInstructionWithToken(token,chatId,url)}
async function loadVkVpnCard(){let response:Response;try{response=await fetch(VK_VPN_CARD_URL)}catch{throw new AppError('TELEGRAM_ERROR','Не удалось загрузить карточку публикации VK',502)}if(!response.ok)throw new AppError('TELEGRAM_ERROR','Не удалось загрузить карточку публикации VK',502);return new Blob([await response.arrayBuffer()],{type:'image/jpeg'})}
export async function sendTelegramVkBackupWithToken(token:string,chatId:string,vkUrl:string){const body=new FormData();body.set('chat_id',chatId);body.set('photo',await loadVkVpnCard(),'vk-publish-vpn.jpg');body.set('reply_markup',JSON.stringify({inline_keyboard:[[{text:'Опубликовать в VK',url:vkUrl}]]}));return callWithToken(token,'sendPhoto',body)}
export async function deleteTelegramMessageWithToken(token:string,chatId:string,messageId:number){const body=new FormData();body.set('chat_id',chatId);body.set('message_id',String(messageId));return callWithToken(token,'deleteMessage',body)}
export async function getTelegramChatMember(env:Env,chatId:string,userId:string){const body=new FormData();body.set('chat_id',chatId);body.set('user_id',userId);return call(env,'getChatMember',body) as Promise<{status:string}>}
export async function getTelegramBotMe(env:Env){return call(env,'getMe') as Promise<{id:number;username?:string;first_name:string;can_manage_bots?:boolean}>}export async function getManagedTelegramBotToken(env:Env,managedBotId:string){const body=new FormData();body.set('user_id',managedBotId);return call(env,'getManagedBotToken',body) as Promise<string>}export async function getTelegramBotMeWithToken(token:string){return callWithToken(token,'getMe') as Promise<{id:number;username?:string;first_name:string}>}export async function setTelegramWebhookWithToken(token:string,webhookUrl:string,secretToken:string){const body=new FormData();body.set('url',webhookUrl);body.set('secret_token',secretToken);body.set('allowed_updates',JSON.stringify(['message','my_chat_member']));return callWithToken(token,'setWebhook',body) as Promise<boolean>}
export async function sendTelegramManagedBotRequest(env:Env,chatId:string,requestId:number,suggestedName:string,suggestedUsername:string){const body=new FormData();body.set('chat_id',chatId);body.set('text','Создайте персонального Telegram-бота для Cosmo Sofa.');body.set('reply_markup',JSON.stringify({keyboard:[[{text:'Создать персонального бота',request_managed_bot:{request_id:requestId,suggested_name:suggestedName,suggested_username:suggestedUsername}}]],resize_keyboard:true,one_time_keyboard:true}));return call(env,'sendMessage',body)}
export async function saveTelegramPreparedManagedBotButton(env:Env,userId:string,requestId:number,suggestedName:string,suggestedUsername:string){const body=new FormData();body.set('user_id',userId);body.set('button',JSON.stringify({text:'Создать персонального бота',request_managed_bot:{request_id:requestId,suggested_name:suggestedName,suggested_username:suggestedUsername}}));return call(env,'savePreparedKeyboardButton',body) as Promise<{id:string}>}
function escapeRichText(text:string){return text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\r?\n/g,'<br>')}
function richHtml(value:TelegramRender|string){if(typeof value==='string')return `<p>${escapeRichText(value)}</p>`;return value.richMessageHtml||value.html||`<p>${escapeRichText(value.plainText)}</p>`}
function photoBlock(index:number){return {type:'photo',photo:{type:'photo',media:`attach://photo${index}`}}}
function mediaBlock(count:number,layout:TelegramPhotoLayout){const photos=Array.from({length:count},(_,index)=>photoBlock(index));if(count===1)return photos[0];return {type:layout,blocks:photos}}
async function publishWithToken(token:string,rendered:TelegramRender|string,image:File|File[]|undefined,chatId:string,layout:TelegramPhotoLayout='slideshow'){const decoded=typeof rendered==='string'?decodeMiniAppRich(rendered):rendered;const value=decoded;const images=(Array.isArray(image)?image:image?[image]:[]).slice(0,10);const html=richHtml(value);if(!html&&!images.length)throw new AppError('INVALID_RICH_TEXT','Некорректное форматирование публикации',400);const keyboard=typeof value==='string'||!value.buttons?.length?undefined:JSON.stringify({inline_keyboard:value.buttons.map(button=>[{text:button.text,url:button.url}])});const body=new FormData();body.set('chat_id',chatId);images.forEach((file,index)=>body.set(`photo${index}`,file,file.name||`photo${index}.jpg`));let richMessage:unknown;if(images.length&&typeof value!=='string'&&value.richMessageBlocks?.length){richMessage={blocks:[mediaBlock(images.length,layout),...value.richMessageBlocks]};}else{richMessage={html};}body.set('rich_message',JSON.stringify(richMessage));if(keyboard)body.set('reply_markup',keyboard);console.log(JSON.stringify({event:'telegram_publication_route',route:'rich_message',imageCount:images.length,layout,serialization:images.length&&typeof value!=='string'&&value.richMessageBlocks?.length?'blocks':'html',hasStructuredRich:typeof value!=='string'&&!!value.richMessageHtml}));const message=await callWithToken(token,'sendRichMessage',body);const delivery_mode=images.length===0?'rich_message':images.length===1?'rich_message_photo':layout==='collage'?'rich_message_collage':'rich_message_slideshow';return{external_id:String(message.message_id),url:url(chatId,message.message_id),delivery_mode}}
export async function publishTelegram(env:Env,rendered:TelegramRender|string,image:File|File[]|undefined,chatId:string,layout:TelegramPhotoLayout='slideshow'){return publishWithToken(env.TELEGRAM_BOT_TOKEN,rendered,image,chatId,layout)}export async function publishTelegramWithToken(token:string,rendered:TelegramRender|string,image:File|File[]|undefined,chatId:string,layout:TelegramPhotoLayout='slideshow'){return publishWithToken(token,rendered,image,chatId,layout)}
