import type {Env} from '../types';import {AppError} from '../types';import {planTelegramPublication,type TelegramRender} from '../../../shared/telegram-renderer';
async function callWithToken(token:string,method:string,body=new FormData()){const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',body});const j=await r.json<any>();if(!r.ok||!j.ok){console.error('Telegram API error',j.error_code);throw new AppError('TELEGRAM_ERROR',`Telegram отклонил запрос${j.error_code?` (код ${j.error_code})`:''}`,502)}return j.result}
async function call(env:Env,method:string,body:FormData){return callWithToken(env.TELEGRAM_BOT_TOKEN,method,body)}
function url(chat:string,id:number){return chat.startsWith('@')?`https://t.me/${chat.slice(1)}/${id}`:undefined}
export async function sendTelegramText(env:Env,chatId:string,text:string){const body=new FormData();body.set('chat_id',chatId);body.set('text',text);return call(env,'sendMessage',body)}

export async function sendTelegramMiniAppButton(env:Env,chatId:string,url:string){const body=new FormData();body.set('chat_id',chatId);body.set('text','Откройте приложение, чтобы создать публикацию.');body.set('reply_markup',JSON.stringify({inline_keyboard:[[{text:'Открыть приложение',web_app:{url}}]]}));return call(env,'sendMessage',body)}
export async function getTelegramChatMember(env:Env,chatId:string,userId:string){const body=new FormData();body.set('chat_id',chatId);body.set('user_id',userId);return call(env,'getChatMember',body) as Promise<{status:string}>}
export async function getTelegramBotMe(env:Env){return call(env,'getMe',new FormData()) as Promise<{id:number;username?:string;first_name:string;can_manage_bots?:boolean}>}
export async function getManagedTelegramBotToken(env:Env,managedBotId:string){const body=new FormData();body.set('user_id',managedBotId);return call(env,'getManagedBotToken',body) as Promise<string>}
export async function getTelegramBotMeWithToken(token:string){return callWithToken(token,'getMe') as Promise<{id:number;username?:string;first_name:string}>}
export async function publishTelegram(env:Env,rendered:TelegramRender|string,image:File|undefined,chatId:string){const rich=typeof rendered!=='string',value=rich?rendered as TelegramRender:{html:rendered as string,plainText:rendered as string,blocks:[],buttons:[]},keyboard=value.buttons?.length?JSON.stringify({inline_keyboard:value.buttons.map(button=>[{text:button.text,url:button.url}])}):undefined,plan=planTelegramPublication(value,!!image),{html,plainText}=value;if(plainText.length>4096)throw new AppError('TELEGRAM_TEXT_TOO_LONG','Telegram: текст не должен превышать 4096 символов',400);let first;if(image){const f=new FormData();f.set('chat_id',chatId);f.set('photo',image,'image');if(plan.type==='photo_with_caption'){f.set('caption',html);if(rich)f.set('parse_mode','HTML');if(keyboard)f.set('reply_markup',keyboard)}first=await call(env,'sendPhoto',f);if(plan.type==='photo_then_text'){const t=new FormData();t.set('chat_id',chatId);t.set('text',html);if(rich)t.set('parse_mode','HTML');if(keyboard)t.set('reply_markup',keyboard);await call(env,'sendMessage',t)}}else{const f=new FormData();f.set('chat_id',chatId);f.set('text',html);if(rich)f.set('parse_mode','HTML');if(keyboard)f.set('reply_markup',keyboard);first=await call(env,'sendMessage',f)}return {external_id:String(first.message_id),url:url(chatId,first.message_id),delivery_mode:plan.type}}
