import { AppError, type Env } from '../types';
import { validateTelegramMiniAppInitData } from './telegram-miniapp-auth';
import { getManagedTelegramBotToken,getTelegramBotMe,getTelegramBotMeWithToken,sendTelegramManagedBotRequest,saveTelegramPreparedManagedBotButton } from './telegram';
import { decryptManagedBotToken,encryptManagedBotToken,type EncryptedManagedBotToken } from './managed-bot-crypto';
import { configureManagedBotWebhook } from './managed-bot-onboarding';
const MANAGER_BOT_USERNAME='cosmo_sofa_bot';const SUGGESTED_NAME='Cosmo Sofa Test';const USERNAME_ALPHABET='abcdefghijklmnopqrstuvwxyz0123456789';
type TelegramUser={id?:unknown;username?:unknown;first_name?:unknown};
export interface ManagedBotTelegramApi{getManagerMe(env:Env):ReturnType<typeof getTelegramBotMe>;getManagedToken(env:Env,botId:string):Promise<string>;getManagedMe(token:string):ReturnType<typeof getTelegramBotMeWithToken>;configureWebhook(env:Env,botId:string,token:string):Promise<string>}
const telegramApi:ManagedBotTelegramApi={getManagerMe:getTelegramBotMe,getManagedToken:getManagedTelegramBotToken,getManagedMe:getTelegramBotMeWithToken,configureWebhook:configureManagedBotWebhook};
function telegramId(value:unknown){return typeof value==='number'&&Number.isSafeInteger(value)?String(value):null}function optionalString(value:unknown){return typeof value==='string'&&value?value:null}function randomSuffix(){const bytes=crypto.getRandomValues(new Uint8Array(6));return[...bytes].map(byte=>USERNAME_ALPHABET[byte%USERNAME_ALPHABET.length]).join('')}export function generateSuggestedManagedBotUsername(){return`cosmo_sofa_${randomSuffix()}_bot`}function randomRequestId(){return crypto.getRandomValues(new Int32Array(1))[0]}
async function configureManagedBotDescription(token:string){const body=new FormData();body.set('description','Здесь будут публиковаться предпросмотры Ваших постов. Пожалуйста, нажмите «Запустить бот».');try{const r=await fetch(`https://api.telegram.org/bot${token}/setMyDescription`,{method:'POST',body});if(!r.ok)console.error({event:'managed_bot_description_failed',status:r.status})}catch(error){console.error({event:'managed_bot_description_failed',errorName:error instanceof Error?error.name:'UNKNOWN'})}}
export async function getManagerBotDiagnostic(env:Env,api:ManagedBotTelegramApi=telegramApi){const bot=await api.getManagerMe(env);const canManageBots=bot.can_manage_bots===true;return{ok:canManageBots,username:bot.username??null,canManageBots}}
export async function createManagedBotLink(request:Request,env:Env){const initData=request.headers.get('authorization')?.match(/^tma\s+(.+)$/i)?.[1]??'';await validateTelegramMiniAppInitData(initData,env.TELEGRAM_BOT_TOKEN);const suggestedUsername=generateSuggestedManagedBotUsername();return{url:`https://t.me/newbot/${MANAGER_BOT_USERNAME}/${suggestedUsername}?name=${encodeURIComponent(SUGGESTED_NAME)}`,suggestedName:SUGGESTED_NAME,suggestedUsername}}
export async function prepareManagedBotCreation(request:Request,env:Env){const initData=request.headers.get('authorization')?.match(/^tma\s+(.+)$/i)?.[1]??'';const validated=await validateTelegramMiniAppInitData(initData,env.TELEGRAM_BOT_TOKEN);const telegramUserId=String(validated.user.id),requestId=randomRequestId(),suggestedUsername=generateSuggestedManagedBotUsername();const prepared=await saveTelegramPreparedManagedBotButton(env,telegramUserId,requestId,SUGGESTED_NAME,suggestedUsername);if(!prepared?.id)throw new AppError('MANAGED_BOT_PREPARE_FAILED','Telegram не вернул идентификатор запроса',502);return{ok:true,requestId:prepared.id,suggestedName:SUGGESTED_NAME,suggestedUsername}}
export async function requestManagedBotCreation(request:Request,env:Env,sendRequest=sendTelegramManagedBotRequest){const initData=request.headers.get('authorization')?.match(/^tma\s+(.+)$/i)?.[1]??'';const validated=await validateTelegramMiniAppInitData(initData,env.TELEGRAM_BOT_TOKEN);const telegramUserId=String(validated.user.id),requestId=randomRequestId(),suggestedUsername=generateSuggestedManagedBotUsername();await sendRequest(env,telegramUserId,requestId,SUGGESTED_NAME,suggestedUsername);console.log({event:'telegram_managed_bot_request_sent',telegramUserId,requestId,suggestedUsername});return{ok:true,requestId,suggestedUsername}}
async function storeManagedBot(env:Env,ownerId:string,botId:string,username:string|null,displayName:string|null,encrypted?:EncryptedManagedBotToken){await env.DB.prepare(`INSERT INTO telegram_managed_bots(id,user_id,telegram_owner_user_id,telegram_bot_id,username,display_name,token_ciphertext,token_iv,token_key_version) VALUES(?,(SELECT user_id FROM telegram_identities WHERE telegram_user_id=?),?,?,?,?,?,?,?) ON CONFLICT(telegram_bot_id) DO UPDATE SET user_id=COALESCE(excluded.user_id,telegram_managed_bots.user_id),telegram_owner_user_id=excluded.telegram_owner_user_id,username=excluded.username,display_name=excluded.display_name,token_ciphertext=COALESCE(excluded.token_ciphertext,telegram_managed_bots.token_ciphertext),token_iv=COALESCE(excluded.token_iv,telegram_managed_bots.token_iv),token_key_version=CASE WHEN excluded.token_ciphertext IS NOT NULL THEN excluded.token_key_version ELSE telegram_managed_bots.token_key_version END,status='active',updated_at=CURRENT_TIMESTAMP`).bind(`tmb_${crypto.randomUUID().replaceAll('-','')}`,ownerId,ownerId,botId,username,displayName,encrypted?.ciphertext??null,encrypted?.iv??null,encrypted?.keyVersion??1).run()}
type ManagedBotCredentialRow={telegram_bot_id:string;username:string|null;token_ciphertext:string|null;token_iv:string|null;token_key_version:number};
export async function getManagedBotCredential(env:Env,userId:string,managedBotId:string){const row=await env.DB.prepare(`SELECT telegram_bot_id,username,token_ciphertext,token_iv,token_key_version FROM telegram_managed_bots WHERE telegram_bot_id=? AND user_id=? AND status='active'`).bind(managedBotId,userId).first<ManagedBotCredentialRow>();if(!row)throw new AppError('MANAGED_BOT_NOT_ACTIVE','Managed bot не найден или не активен',404);if(!row.token_ciphertext||!row.token_iv)throw new AppError('MANAGED_BOT_CREDENTIAL_MISSING','Для managed bot ещё не сохранён credential',409);const token=await decryptManagedBotToken(row.telegram_bot_id,{ciphertext:row.token_ciphertext,iv:row.token_iv,keyVersion:row.token_key_version},env);return{botId:row.telegram_bot_id,token,username:row.username}}
export async function handleManagedBotUpdate(update:any,env:Env,api:ManagedBotTelegramApi=telegramApi){if(update?.managed_bot!==undefined){const managed=update.managed_bot,ownerId=telegramId(managed?.user?.id),botId=telegramId(managed?.bot?.id);if(!ownerId||!botId){console.log({event:'telegram_managed_bot_invalid'});return true}const username=optionalString((managed.bot as TelegramUser).username),displayName=optionalString((managed.bot as TelegramUser).first_name);console.log({event:'telegram_managed_bot_updated',telegramUserId:ownerId,managedBotId:botId,managedBotUsername:username,managedBotName:displayName});const token=await api.getManagedToken(env,botId);if(typeof token!=='string'||!token)throw new AppError('MANAGED_BOT_TOKEN_INVALID','Telegram не вернул token managed bot',502);const verifiedBot=await api.getManagedMe(token);if(telegramId(verifiedBot.id)!==botId)throw new AppError('MANAGED_BOT_TOKEN_INVALID','Telegram вернул token другого managed bot',502);const encrypted=await encryptManagedBotToken(botId,token,env);await storeManagedBot(env,ownerId,botId,username,displayName,encrypted);await Promise.all([api.configureWebhook(env,botId,token),configureManagedBotDescription(token)]);console.log({event:'telegram_managed_bot_token_verified',managedBotId:botId,managedBotUsername:optionalString(verifiedBot.username)??username,verified:true});return true}if(update?.message?.managed_bot_created!==undefined){const message=update.message,ownerId=telegramId(message?.from?.id),bot=message?.managed_bot_created?.bot,botId=telegramId(bot?.id);if(!ownerId||!botId){console.log({event:'telegram_managed_bot_created_message_invalid'});return true}const username=optionalString((bot as TelegramUser).username),displayName=optionalString((bot as TelegramUser).first_name);await storeManagedBot(env,ownerId,botId,username,displayName);return true}return false}
