import { AppError, type Env } from '../types';
import { validateTelegramMiniAppInitData } from './telegram-miniapp-auth';
import { resolveOrCreateTelegramIdentity } from './telegram-identity';
const MAX_BYTES=5*1024*1024;
function initDataFrom(request:Request){return request.headers.get('authorization')?.match(/^tma\s+(.+)$/i)?.[1]??''}
async function account(request:Request,env:Env){const validated=await validateTelegramMiniAppInitData(initDataFrom(request),env.TELEGRAM_BOT_TOKEN);return resolveOrCreateTelegramIdentity(env,String(validated.user.id))}
const prefix=(userId:string)=>`watermarks/${userId}/`;
export async function listWatermarks(request:Request,env:Env){const a=await account(request,env),p=prefix(a.userId);const result=await env.IMAGES.list({prefix:p,include:['customMetadata']});return{watermarks:result.objects.map(o=>({id:o.key.slice(p.length),name:o.customMetadata?.name||'Водяной знак'}))}}
export async function uploadWatermark(request:Request,env:Env){const a=await account(request,env);const form=await request.formData().catch(()=>{throw new AppError('INVALID_FORM_DATA','Не удалось прочитать изображение',400)});const file=form.get('image');if(!(file instanceof File)||!file.size)throw new AppError('INVALID_IMAGE','Выберите изображение',400);if(!file.type.startsWith('image/'))throw new AppError('INVALID_IMAGE_TYPE','Можно загрузить только изображение',400);if(file.size>MAX_BYTES)throw new AppError('IMAGE_TOO_LARGE','Водяной знак должен быть не больше 5 МБ',400);const id=`wm_${Date.now()}_${crypto.randomUUID().slice(0,8)}.png`;await env.IMAGES.put(prefix(a.userId)+id,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{name:file.name.slice(0,120)}});return{id,name:file.name}}
export async function getWatermark(request:Request,env:Env,id:string){const a=await account(request,env);const object=await env.IMAGES.get(prefix(a.userId)+id);if(!object)throw new AppError('NOT_FOUND','Водяной знак не найден',404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('cache-control','private, max-age=86400');headers.set('etag',object.httpEtag);return new Response(object.body,{headers})}
export async function deleteWatermark(request:Request,env:Env,id:string){const a=await account(request,env),key=prefix(a.userId)+id;const object=await env.IMAGES.head(key);if(!object)throw new AppError('NOT_FOUND','Водяной знак не найден',404);await env.IMAGES.delete(key);return{ok:true}}
