const VK_APP_ID=54742219,VK_API_VERSION='5.199';
const $=id=>document.getElementById(id),status=$('status'),groupsEl=$('groups'),diagnostics=$('diagnostics'),logEl=$('diagnostic-log');
function params(){const q=new URLSearchParams(location.hash.replace(/^#/,''));return{token:q.get('connect')||'',callback:q.get('callback')||''}}
function safeError(error){return JSON.stringify(error,(k,v)=>/token/i.test(k)?'***':v,2)}
function log(text){if(logEl)logEl.textContent+=(logEl.textContent?'\n':'')+text;console.log(text)}
function diag(label,value){let text=value;try{if(typeof value!=='string')text=JSON.stringify(value,(k,v)=>/token|authorization/i.test(k)?'***':v)}catch{text=String(value)}log(`${label}: ${text}`)}
function showSuccess(group){$('picker-view').hidden=true;$('success-view').hidden=false;$('selected-group-name').textContent=group.name||'Группа VK';$('selected-group-url').textContent=group.screen_name?`vk.com/${group.screen_name}`:`ID ${group.id}`}
async function closeMiniApp(){const button=$('close-vk-onboarding');if(button){button.disabled=true;button.textContent='Закрываем…'}try{await vkBridge.send('VKWebAppClose',{status:'success'})}catch(error){log('CLOSE ERROR '+safeError(error));try{history.go(-1)}catch{}if(button){button.disabled=false;button.textContent='Закрыть'}}}
async function init(){const {token,callback}=params();diagnostics.open=true;diag('BUILD','vk-save-diag-20260901-2');diag('LOCATION',{origin:location.origin,search:location.search,hashKeys:[...new URLSearchParams(location.hash.replace(/^#/,'')).keys()]});diag('HANDOFF',{tokenPresent:!!token,tokenLength:token.length,callback});$('close-vk-onboarding')?.addEventListener('click',closeMiniApp);if(!token||!callback){status.textContent='Ссылка подключения недействительна.';return}try{await vkBridge.send('VKWebAppInit');diag('VKWebAppInit','OK');status.textContent='Получаем ваши группы…';const auth=await vkBridge.send('VKWebAppGetAuthToken',{app_id:VK_APP_ID,scope:'groups'});diag('AUTH',{accessTokenPresent:!!auth?.access_token});const result=await vkBridge.send('VKWebAppCallAPIMethod',{method:'groups.get',params:{access_token:auth.access_token,filter:'admin',extended:1,count:100,v:VK_API_VERSION}});const items=Array.isArray(result?.response?.items)?result.response.items:[];diag('groups.get',{ok:true,count:items.length});if(!items.length){status.textContent='Не найдено групп, которыми вы управляете.';return}status.textContent='Нажмите на группу, которую хотите подключить.';groupsEl.hidden=false;for(const group of items){const b=document.createElement('button');b.type='button';b.className='group-button';const photo=group.photo_100||group.photo_50||'';b.innerHTML=`${photo?`<img src="${photo}" alt="">`:''}<span><strong>${group.name||'Группа VK'}</strong><small>${group.screen_name?`vk.com/${group.screen_name}`:`ID ${group.id}`}</small></span>`;b.addEventListener('click',()=>selectGroup(group,token,callback));groupsEl.appendChild(b)}}catch(error){status.textContent='Не удалось получить список групп.';log('ERROR '+safeError(error));diagnostics.open=true}}
async function selectGroup(group,token,callback){[...groupsEl.querySelectorAll('button')].forEach(b=>b.disabled=true);status.textContent='Сохраняем группу…';diagnostics.open=true;const launchUser=new URLSearchParams(location.search).get('vk_user_id')||'';const endpoint=`${callback.replace(/\/+$/,'')}/api/vk-onboarding/${encodeURIComponent(token)}`;diag('SAVE START',{groupId:group.id,groupName:group.name||'',screenName:group.screen_name||'',vkUserId:launchUser||null,callback,endpointOrigin:(()=>{try{return new URL(endpoint).origin}catch{return'INVALID URL'}})()});const controller=new AbortController(),timer=setTimeout(()=>{diag('SAVE TIMEOUT','10000ms reached; aborting fetch');controller.abort('vk-save-timeout')},10000);try{const started=Date.now();diag('FETCH CALL','starting cross-origin POST');const response=await fetch(endpoint,{method:'POST',mode:'cors',headers:{'content-type':'application/json'},body:JSON.stringify({vkUserId:launchUser,groupId:group.id,groupName:group.name||'',screenName:group.screen_name||''}),signal:controller.signal});diag('SAVE RESPONSE',{ms:Date.now()-started,status:response.status,statusText:response.statusText,ok:response.ok,type:response.type,url:response.url,contentType:response.headers.get('content-type'),cors:response.headers.get('access-control-allow-origin')});const raw=await response.text();diag('SAVE BODY',raw.slice(0,1000)||'<empty>');let data=null;try{data=raw?JSON.parse(raw):null}catch{}if(!response.ok)throw new Error(data?.error?.message||`HTTP ${response.status}`);diag('SAVE RESULT','OK');showSuccess(group);vkBridge.send('VKWebAppTapticNotificationOccurred',{type:'success'}).catch(()=>{})}catch(error){status.textContent=controller.signal.aborted?'Сервер не ответил за 10 секунд.':error instanceof Error?error.message:'Не удалось сохранить группу.';[...groupsEl.querySelectorAll('button')].forEach(b=>b.disabled=false);diag('SAVE ERROR',{name:error?.name||'',message:error?.message||String(error),aborted:controller.signal.aborted,abortReason:controller.signal.aborted?String(controller.signal.reason):null,online:navigator.onLine})}finally{clearTimeout(timer)}}
init();
